--[[
    init.lua
    Created: 05/15/2024 09:57:13
    Description: Autogenerated script file for the map debug_test.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local debug_test = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---debug_test.Init(zone)
--Engine callback function
function debug_test.Init(zone)


end

---debug_test.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function debug_test.EnterSegment(zone, rescuing, segmentID, mapID)


end

---debug_test.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function debug_test.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---debug_test.Rescued(zone, name, mail)
--Engine callback function
function debug_test.Rescued(zone, name, mail)


end

return debug_test

