--[[
    init.lua
    Created: 06/04/2024 14:47:10
    Description: Autogenerated script file for the map peaceful_lake.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local peaceful_lake = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---peaceful_lake.Init(zone)
--Engine callback function
function peaceful_lake.Init(zone)


end

---peaceful_lake.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function peaceful_lake.EnterSegment(zone, rescuing, segmentID, mapID)


end

---peaceful_lake.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function peaceful_lake.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---peaceful_lake.Rescued(zone, name, mail)
--Engine callback function
function peaceful_lake.Rescued(zone, name, mail)


end

return peaceful_lake

