--[[
    init.lua
    Created: 05/20/2024 12:15:47
    Description: Autogenerated script file for the map gelid_woods.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local gelid_woods = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---gelid_woods.Init(zone)
--Engine callback function
function gelid_woods.Init(zone)


end

---gelid_woods.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function gelid_woods.EnterSegment(zone, rescuing, segmentID, mapID)


end

---gelid_woods.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function gelid_woods.ExitSegment(zone, result, rescue, segmentID, mapID)
  
    if result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then --you or your partner fainted.
        if SV.progression.chapter == 2 then --if it's chapter two, it will warp you out of the dungeon to the beggining.
            GAME:EndDungeonRun(result, "gelid_woods", -1, 0, 1, false, false)
            GAME:EnterZone("gelid_woods", -1, 0, 1)


        else --otherwise, to the guild and end the day.


        end

    else --you beat it.
        if segmentID == 1 then
           --Go to the ground map too but set the variable to true
            SV.gelid_woods.beat_boss = true
            GAME:EnterZone("gelid_woods", -1, 1, 0)

           
        elseif segmentID == 0 then
            --Go to the ground map
            GAME:EnterZone("gelid_woods", -1, 1, 0)
            

        end

    end
   
end

---gelid_woods.Rescued(zone, name, mail)
--Engine callback function
function gelid_woods.Rescued(zone, name, mail)


end

return gelid_woods

