--[[
    init.lua
    Created: 12/31/2023 21:00:50
    Description: Autogenerated script file for the map guild_storage_room.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local guild_storage_room = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_storage_room.Init(map)
--Engine callback function
function guild_storage_room.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---guild_storage_room.Enter(map)
--Engine callback function
function guild_storage_room.Enter(map)

  GAME:FadeIn(20)

end

---guild_storage_room.Exit(map)
--Engine callback function
function guild_storage_room.Exit(map)


end

---guild_storage_room.Update(map)
--Engine callback function
function guild_storage_room.Update(map)


end

---guild_storage_room.GameSave(map)
--Engine callback function
function guild_storage_room.GameSave(map)


end

---guild_storage_room.GameLoad(map)
--Engine callback function
function guild_storage_room.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return guild_storage_room

