--[[
    init.lua
    Created: 05/17/2024 19:53:37
    Description: Autogenerated script file for the map twilight_town.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local twilight_town = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---twilight_town.Init(zone)
--Engine callback function
function twilight_town.Init(zone)


end

---twilight_town.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function twilight_town.EnterSegment(zone, rescuing, segmentID, mapID)


end

---twilight_town.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function twilight_town.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---twilight_town.Rescued(zone, name, mail)
--Engine callback function
function twilight_town.Rescued(zone, name, mail)


end

return twilight_town

