--[[
    init.lua
    Created: 04/30/2024 11:29:26
    Description: Autogenerated script file for the map eve_and_dex.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local room_eve_and_dex = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---eve_and_dex.Init(map)
--Engine callback function
function room_eve_and_dex.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies()
  local partners = CH('Teammate1')
  AI:SetCharacterAI(partners, "ai.ground_partner", CH('PLAYER'), partners.Position)
  AI:EnableCharacterAI(partners)
  partners.CollisionDisabled = true
end

---eve_and_dex.Enter(map)
--Engine callback function
function room_eve_and_dex.Enter(map)

  GAME:FadeIn(20)

end

---eve_and_dex.Exit(map)
--Engine callback function
function room_eve_and_dex.Exit(map)


end

---eve_and_dex.Update(map)
--Engine callback function
function room_eve_and_dex.Update(map)


end

---eve_and_dex.GameSave(map)
--Engine callback function
function room_eve_and_dex.GameSave(map)
  local partner = CH('Teammate1')
  SV.partner.positionX = partner.Position.X
	SV.partner.positionY = partner.Position.Y
	SV.partner.direction = DirToNum(partner.Direction)

end

---eve_and_dex.GameLoad(map)
--Engine callback function
function room_eve_and_dex.GameLoad(map)
  local partners = CH('Teammate1')
  GROUND:TeleportTo(partners, SV.partner.positionX, SV.partner.positionY, NumToDir(SV.partner.direction))
  

	AI:SetCharacterAI(partners, "ai.ground_partner", CH('PLAYER'), partners.Position)
  AI:EnableCharacterAI(partners)
  partners.CollisionDisabled = true
  
  GAME:FadeIn(20)

end
function Dialogue(sp, state, emote, txt)
  if state == 0 then --Speaker is unknown and invisible
    UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  elseif state == 1 then --Speaker is unknown, but visible (AKA, you don't know their name)
    UI:SetSpeaker(STRINGS:Format("\\uE040"), true, sp.CurrentForm.Species, sp.CurrentForm.Form, sp.CurrentForm.Skin, sp.CurrentForm.Gender)
  elseif state == 2 then --Speaker is thinking to themselves. (Parenthesis are NOT included here.)
    UI:SetSpeaker("", true, sp.CurrentForm.Species, sp.CurrentForm.Form, sp.CurrentForm.Skin, sp.CurrentForm.Gender)
  else --Speaker speaks regularly
    UI:SetSpeaker(sp)
  end
  UI:SetSpeakerEmotion(emote)
  UI:WaitShowDialogue(txt)


end

function DirToNum(dir)
	--up is 0, upright is 1, ... up left is 7
	local num = -1
	if dir == Direction.Up then
		num = 0
	elseif dir == Direction.UpRight then
		num = 1
	elseif dir == Direction.Right then
		num = 2
	elseif dir == Direction.DownRight then
		num = 3
	elseif dir == Direction.Down then
		num = 4
	elseif dir == Direction.DownLeft then
		num = 5
	elseif dir == Direction.Left then
		num = 6
	elseif dir == Direction.UpLeft then
		num = 7
	end
	
	return num
	
end
--converts a number to a direction
function NumToDir(num)
	local dir = Direction.None
	if num % 8 == 0 then 
		dir = Direction.Up
	elseif num % 8 == 1 then
		dir = Direction.UpRight
	elseif num % 8 == 2 then
		dir = Direction.Right
	elseif num % 8 == 3 then
		dir = Direction.DownRight
	elseif num % 8 == 4 then
		dir = Direction.Down
	elseif num % 8 == 5 then
		dir = Direction.DownLeft
	elseif num % 8 == 6 then
		dir = Direction.Left
	elseif num % 8 == 7 then
		dir = Direction.UpLeft
	end

	return dir
end 
-------------------------------
-- Entities Callbacks
-------------------------------
function room_eve_and_dex.book1_Action(obj, activator)
  GAME:CutsceneMode(true)

  UI:ResetSpeaker()
  UI:WaitShowDialogue("It's a book about a loving couple forcingly separated by their own rival families.")
  GAME:CutsceneMode(false)

end
function room_eve_and_dex.book2_Action(obj, activator)
  GAME:CutsceneMode(true)

  UI:ResetSpeaker()
  UI:WaitShowDialogue('A book titled "Medicine and how to cause the need for it".')
  GAME:CutsceneMode(false)

end
function room_eve_and_dex.exit_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  SV.partner.entrance = 1
	GAME:EnterZone('thieves_hideout', -1, 11, 1)
  
end
function room_eve_and_dex.Eve_Action(obj, activator)
  local player = activator
  local partner = CH('Teammate1')
  local eve = obj
	GAME:CutsceneMode(true)

 
  if not SV.guild.presented_to_eve then
  

    GAME:FadeOut(false, 20)
    local marker = MRKR('1')
    local marker2 = MRKR('2')
    AI:DisableCharacterAI(partner)
		GROUND:TeleportTo(player, marker.Position.X, marker.Position.Y, marker.Direction)
		GROUND:TeleportTo(partner, marker2.Position.X, marker2.Position.Y, marker2.Direction)
    GAME:WaitFrames(50)
    GAME:FadeIn(20)


    Dialogue(eve, 1, "Stunned", "I've gotta be careful now...[br]Just one drop more than necessary and this antidote will turn into a toxic beverage!")
    GAME:WaitFrames(50)
    Dialogue(eve, 1, "Worried", "...")
    GAME:WaitFrames(60)
    Dialogue(eve, 1, "Special1", "Maybe I should do that...[br]I already have enough of them anyway.")

    Dialogue(partner, 3, "Normal", "Hi, " .. eve:GetDisplayName()..".")

    SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
		GROUND:CharSetEmote(eve, "exclaim", 1)
    GROUND:CharTurnToCharAnimated(eve, partner, 3)
    --  SOUND:FadeOutBGM(60)
    GAME:WaitFrames(20)
    Dialogue(eve, 3, "Surprised", "[color=#00ffff]Ma'am[color], I swear I didn't take more of your poison while you were asleep!")
    GAME:WaitFrames(90)

    Dialogue(eve, 3, "Stunned", "Oh, it's just you, "..partner:GetDisplayName().."...")
    GAME:WaitFrames(50)
   

    Dialogue(partner, 3, "Worried", "...")

    GAME:WaitFrames(70)
    Dialogue(partner, 3, "Worried", "Do you use [color=#00ff00]Salazzle[color] poison in your medicine?")
    GAME:WaitFrames(60)

    Dialogue(eve, 3, "Happy", "Well, sometimes!")
    Dialogue(eve, 3, "Happy", "It's highly toxic, but it's got some interesting uses if diluted correctly!")
    GAME:WaitFrames(50)
    Dialogue(eve, 3, "Special1", "And many more if not...")
    GAME:WaitFrames(30)

		SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
		GROUND:CharSetEmote(player, "sweatdrop", 1)
		GROUND:CharSetEmote(partner, "sweatdrop", 1)
    GAME:WaitFrames(90)
    Dialogue(eve, 3, "Normal", "But anyway.[br]What do you need?")
    Dialogue(eve, 3, "Worried", "Are you hurt?[br]Do you need a check up?")
    GAME:WaitFrames(50)
    Dialogue(partner, 3, "Stunned", "Errm...[pause=30] No, don't worry.")

    GROUND:CharTurnToCharAnimated(partner, player, 5)
    GROUND:CharTurnToCharAnimated(eve, player, 5)

    Dialogue(partner, 3, "Normal", "This is "..player:GetDisplayName()..".[br]He's a new member of the guild.")
   
    GAME:WaitFrames(60)

    Dialogue(eve, 3, "Worried", "A new member?")
    Dialogue(eve, 3, "Happy", "Well, nice to meet you, "..player:GetDisplayName().."!")
    Dialogue(eve, 3, "Normal", "I'm "..eve:GetDisplayName()..", the guild's medic!")
    Dialogue(eve, 3, "Happy", "If you ever feel ill or get too injured in a battle, just come and see me and I'll get you patched up in no time!")

    Dialogue(eve, 3, "Happy", "And if you actually end up here because of someone hurting you...")
    Dialogue(eve, 3, "Normal", "Well...")

    Dialogue(eve, "Happy", "May the gods have mercy on them,[pause=40] because I sure won't. " .. STRINGS:Format("\\u2661"))
    --Dialogue(eve, 3, "Happy", "May the gods have mercy on them,[pause=40] because I sure won't.") 


		SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
		GROUND:CharSetEmote(player, "sweatdrop", 1)

    GAME:WaitFrames(90)

    Dialogue(player, 3, "Stunned", "Uhh...[pause=40] thank you?")
    GROUND:CharTurnToCharAnimated(player, partner, 5)
    Dialogue(player, 3, "Stunned", "Should I be concerned?")

    GROUND:CharTurnToCharAnimated(partner, player, 5)
    GAME:WaitFrames(50)
    Dialogue(partner, 3, "Worried", "Well...")
    Dialogue(partner, 3, "Worried", "Not too much.")
    GAME:WaitFrames(60)
    GROUND:CharTurnToCharAnimated(partner, eve, 4)
    GROUND:CharTurnToCharAnimated(player, eve, 4)

    Dialogue(partner, 3, "Normal", "Anyway,[pause=30] the point is that if you feel like you need a medic, she's the one you should go to.")
    Dialogue(eve, 3, "Joyous", "Yup![br]I'm free to help at anytime!") 
    Dialogue(eve, 3, "Normal", "Oh, and "..player:GetDisplayName()..".") 
    Dialogue(player, 3, "Normal", "Yeah?")
    Dialogue(eve, 3, "Normal", "You know how my medicine is hand-made?") 
    GAME:WaitFrames(70)

    Dialogue(player, 3, "Stunned", "Is it?")
    Dialogue(eve, 3, "Happy", "Yup!") 
    Dialogue(eve, 3, "Sad", "But some of the most complicated potions rarely work well on my first try...") 
    Dialogue(eve, 3, "Normal", "That's why I always try them with the wild Pokémon inside Mystery Dungeons.") 
    Dialogue(eve, 3, "Sad", "The problem is that it's hard to test stuff like antidepressants with them...") 
    Dialogue(eve, 3, "Normal", "So if you ever have some free time to spare, maybe you could come here and try them!") 
    GAME:WaitFrames(70)
    Dialogue(player, 3, "Stunned", "But isn't drinking untested medicine dangerous?")
    Dialogue(eve, 3, "Determined", "Hey![br]Do you not trust my ability as a medic!") 
    Dialogue(eve, 3, "Determined", "I only had an accident once, I'll let you know![br]And honestly, I'm sure [color=#00ffff]Kathy[color] didn't mind her week-long vacation due to severe poisoning!") 

    SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
		GROUND:CharSetEmote(player, "sweatdrop", 1)
		GROUND:CharSetEmote(partner, "sweatdrop", 1)
    Dialogue(player, 3, "Stunned", "Erm...[br]I'll think about it.")
    GAME:WaitFrames(50)
    Dialogue(eve, 3, "Worried", "Weird how that's the only answer I've been getting recently...") 
    GAME:WaitFrames(70)
    Dialogue(player, 2, "Stunned", "(Weird?)") 
    Dialogue(eve, 3, "Happy", "Well, anyway.[pause=40] It was nice meeting you, "..player:GetDisplayName().."!")
    Dialogue(eve, 3, "Normal", "I'm gonna go back to finishing this antidote now.")
    Dialogue(eve, 3, "Worried", "Or poison.[pause=0] I haven't really decided yet...")
    GAME:WaitFrames(70)

    Dialogue(player, 3, "Stunned", "Good luck then, I guess.")
    Dialogue(player, 3, "Stunned", "We'll leave you to it now.")
    Dialogue(eve, 3, "Happy", "Goodbye, you two!")
    
    SV.guild.presented_to_eve = true
    GAME:FadeOut(false, 20)
   
    GROUND:EntTurn(eve, Direction.Right)
    GAME:CutsceneMode(false)
    GAME:FadeIn(20)
    AI:SetCharacterAI(partner, "ai.ground_partner", CH('PLAYER'), partner.Position)
    AI:EnableCharacterAI(partner)
    partner.CollisionDisabled = true
   -- SOUND:PlayBGM("Wigglytuff's Guild.ogg", true) 






  else
    if not SV.guildmasters_office.officially_joined then
      GROUND:CharTurnToChar(partner, eve)
      GROUND:CharTurnToChar(player, eve)
      GROUND:CharTurnToChar(eve, player)

      Dialogue(eve, 3, "Worried", "I'm sorry, but I should really finish this for as soon as I can!")
      Dialogue(eve, 3, "Happy", "But tell me if you want to test any of my medicine!")



      GROUND:EntTurn(eve, Direction.Right)
    else
      if SV.progression.chapter == 2 then
        if not SV.progression.first_day_done then
          GROUND:CharTurnToChar(obj, activator)
          CommonFunctions.Dialogue(obj, 3, "Worried", "Yeah, I'm still doing this antidote.")
          CommonFunctions.Dialogue(obj, 3, "Happy", "Hopefully I will have it done for when you come back!")
          CommonFunctions.Dialogue(obj, 3, "Happy", "And don't forget to tell me if anything hurts too bad after you come back!")
    
          GROUND:EntTurn(obj, Direction.Right)
    
    
    
        end
    
    
    
      end



    end
  end
	GAME:CutsceneMode(false)

end
return room_eve_and_dex

