--[[
    init.lua
    Created: 01/01/2024 17:07:46
    Description: Autogenerated script file for the map interrogation.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local interrogation = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---interrogation.Init(map)
--Engine callback function
function interrogation.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---interrogation.Enter(map)
--Engine callback function
function interrogation.Enter(map)
  GAME:CutsceneMode(true)
  GROUND:Hide('Partner')
  GROUND:Hide('Kit')
  GROUND:Hide('Lilith')
  local level = _DATA.Save.ActiveTeam.Leader.Level

  local assembly_count = GAME:GetPlayerAssemblyCount()
  for i = 1, assembly_count, 1 do
    _DATA.Save.ActiveTeam.Assembly.RemoveAt(i-1)
    
  end 

  _DATA.Save.ActiveTeam:SetRank("unranked")
  --_DATA.Save.ActiveTeam.Money = 0
  --_DATA.Save.ActiveTeam.Bank = 0
  _DATA.Save.NoSwitching = true

  local party_count = _DATA.Save.ActiveTeam.Players.Count
  for ii = 1, party_count, 1 do
    _DATA.Save.ActiveTeam.Players:RemoveAt(0)
  end





  _DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, RogueEssence.Dungeon.MonsterID("riolu", 0, "normal", Gender.Male), 5, "inner_focus", 0))
  _DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, RogueEssence.Dungeon.MonsterID("sprigatito", 0, "normal", Gender.Female), level, "overgrow", 1))

  _DATA.Save.ActiveTeam.Players[0]:FullRestore()
  _DATA.Save.ActiveTeam.Players[1]:FullRestore()



  GAME:SetTeamLeaderIndex(0)

  _DATA.Save:UpdateTeamProfile(true)
  _DATA.Save.ActiveTeam.Players[0].IsFounder = true
  _DATA.Save.ActiveTeam.Players[0].IsPartner = true


  _DATA.Save.ActiveTeam.Players[1].IsFounder = true
  _DATA.Save.ActiveTeam.Players[1].IsPartner = true
  local player = CH('PLAYER')
  local partner = CH('Partner')
  

 -- [[
  GAME:MoveCamera(96, 72, 1, false)
  GROUND:CharSetAction(player, RogueEssence.Ground.PoseGroundAction(player.Position, player.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Laying")))
  
  GAME:WaitFrames(100)
  GAME:FadeIn(220)

  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(40)
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)

  GAME:WaitFrames(120)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Ugh...")
  UI:WaitShowDialogue("Where...[pause=60] Where am I?")
  UI:WaitShowDialogue("I can barely move...")

  GAME:WaitFrames(70)
  UI:WaitShowDialogue("What happened?")


  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)

  GAME:WaitFrames(40)
  UI:WaitShowDialogue("Look who finally decided to wake up!")
  UI:WaitShowDialogue("You've taken your sweet time, haven't you?")
  UI:WaitShowDialogue("On your feet, [color=#00ff00]Riolu[color]. And don't make us wait.")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("What?")
  UI:WaitShowDialogue("Who's there?")
  GAME:WaitFrames(60)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Are you deaf?")
  UI:WaitShowDialogue("On your feet!")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("W-[pause=40]What?")
   GAME:WaitFrames(40)
  UI:WaitShowDialogue("O-[pause=60]Okay...")
 --]]
  GROUND:CharSetAnim(player, "Wake", false)
  GAME:WaitFrames(100)
 -- [[
  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(30)
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)

  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Ow...")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Quit your stupid whining already and let's start with this bullshit now.")

  GAME:WaitFrames(50)
  UI:WaitShowDialogue("First off, what's your name?")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("My[pause=40]-My name?")
  GAME:WaitFrames(40)
  Hop(player, 'None', 10, 10, false, true)
  SOUND:PlaySE("Battle/EVT_Emote_Complain_2")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("YES YOUR NAME!")
  UI:WaitShowDialogue("KEEP WASTING OUR TIME LIKE THAT AND YOU'RE GONNA END UP WITH SOMETHING FAR WORSE THAN THE CONCUSSION FROM BEFORE!")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("O-Okay...")
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Sorry.")
  GAME:WaitFrames(60)

  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("(How am I gonna tell them my name?)")
  UI:WaitShowDialogue("(I don't know it myself!)")
  UI:WaitShowDialogue("(I'll have to make something up...)")
  --]]
  local loop = false 
	while not loop do
		UI:NameMenu("What is my name?", "", 60)
		UI:WaitForChoice()
		name = UI:ChoiceResult()
      if name == "" then 
        name = _DATA:GetMonster(GAME:GetPlayerPartyMember(0).CurrentForm.Species).Name:ToLocal() 
      end
  
      
		UI:ChoiceMenuYesNo("(Is [color=#009CFF]" .. name .. "[color] really my name?)")
		UI:WaitForChoice()
		loop = UI:ChoiceResult()
	end
  local hero = GAME:GetPlayerPartyMember(0)

  GAME:SetCharacterNickname(hero, name)
  -- [[
  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue(STRINGS:Format("{0}! My name is {0}!", player:GetDisplayName()))
  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue(STRINGS:Format("{0}? That's a stupid name.", player:GetDisplayName()))
  UI:WaitShowDialogue("Whatever, I'm not here to judge.")
  UI:WaitShowDialogue("Next quetion. What were you doing in the middle of the clearing where we found you?")
  GAME:WaitFrames(80)
  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(Clearing?)")
  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("(Wait!)")
  GAME:WaitFrames(70)

  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("(That [color=#fff30a]Sprigatito[color]!)")
  UI:WaitShowDialogue("(She's the one that got me into this mess!)")
  UI:WaitShowDialogue("(If I see her again, I swear I'll-!)")

  
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim')
  GROUND:CharSetEmote(player, "notice", 1)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue(STRINGS:Format('Last warning, "{0}".', player:GetDisplayName()))
  UI:WaitShowDialogue("If I have to remind you to answer my questions again, I'll be firced to use force.")
  UI:WaitShowDialogue("And trust me,[pause=60] you DON'T want me to use force.")

  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Sorry.")

  GAME:WaitFrames(80)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Hopefully you'll understand this time.")
  UI:WaitShowDialogue("Now, what were you doing in that clearing?")

  GAME:WaitFrames(80)

  GROUND:EntTurn(player, Direction.DownLeft)
  GAME:WaitFrames(80)
  GROUND:EntTurn(player, Direction.DownRight)

  GAME:WaitFrames(60)

  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(30)
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)

  GAME:WaitFrames(50)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("I can't remember.")

  GAME:WaitFrames(80)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Do you really think we are going to believe that?")

  UI:WaitShowDialogue("Who do you take us for?")
 

  GAME:WaitFrames(120)
  UI:WaitShowDialogue("Maybe he's telling the truth?")

  GROUND:EntTurn(player, Direction.Down)
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
  GROUND:CharSetEmote(player, "exclaim", 1)
  GAME:WaitFrames(100)
  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(That voice...)")
  GAME:WaitFrames(70)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Hey! Keep quiet! Let them do the work!")


  UI:WaitShowDialogue("No,[pause=50] YOU keep quiet!")
  UI:WaitShowDialogue("I'll express my opinion if I want to!")
  GAME:WaitFrames(70)
  UI:WaitShowDialogue("You really shouldn't in the middle of this...")
  GAME:WaitFrames(80)

  UI:WaitShowDialogue("Stop fighting while we are in an interrogation!")
  GAME:WaitFrames(60)
  UI:WaitShowDialogue("The nerve...")


  GROUND:CharSetEmote(player, "shock", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Shock')
  GAME:WaitFrames(100)
  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("(It's her!)")
  GAME:WaitFrames(40)
  GROUND:CharSetEmote(player, "angry", 2)
  SOUND:PlaySE("Battle/EVT_Emote_Complain_2")
  Hop(player, 'None', 10)
  Hop(player, 'None', 10)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("It's you!")
  UI:WaitShowDialogue("You are the [color=#fff30a]Sprigatito[color] that was in that clearing!")
  GAME:WaitFrames(70)
  UI:WaitShowDialogue("How could you do this?[pause=0] I trusted you!")
  
  SOUND:PlayBattleSE("EVT_Battle_Flash")
  GAME:FadeOut(true, 1)
  GROUND:CharSetAction(player, RogueEssence.Ground.PoseGroundAction(player.Position, player.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pain")))
  GAME:WaitFrames(6)
  GAME:FadeIn(1)
 
 -- GAME:WaitFrames(16)
 

  GAME:WaitFrames(60)
  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(30)
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(80)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Ow!")
  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("(Where did that attack come from?)")
  UI:WaitShowDialogue("(I can't see anyone other than me in here.)")
  UI:WaitShowDialogue("(What kind of darkness is this?)")

  GAME:WaitFrames(40)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue(STRINGS:Format("New rule, {0}. You only speak when spoken to, got it?", player:GetDisplayName()))
  UI:WaitShowDialogue("Or I won't hold back next time.")

  GAME:WaitFrames(70)
  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("(He was holding back?)")
  
  GAME:WaitFrames(80)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Now on your feet.")
  GAME:WaitFrames(30)
  GROUND:CharSetAnim(player, "Wake", false)
  GROUND:EntTurn(player, Direction.Down)

  GAME:WaitFrames(70)
  UI:WaitShowDialogue("I'll only repeat the question once.")
  UI:WaitShowDialogue("What were you doing in that clearing?")
  UI:WaitShowDialogue("You were found laying unconsciouss in a clearing at the end of a Mystery Dungeon.")
  UI:WaitShowDialogue("Isn't it too convenient that happened after one of or teams was being chased?")
  UI:WaitShowDialogue(STRINGS:Format("Now give us an answer, {0}.", player:GetDisplayName()))
  GAME:WaitFrames(100)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("...[pause=60]")
  GAME:WaitFrames(70)
  UI:WaitShowDialogue("I don't know.")
  UI:WaitShowDialogue("I can't remember anything.")
  GAME:WaitFrames(70)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue(".[pause=30].[pause=30].[pause=30]")
 

  UI:WaitShowDialogue("We're not getting anywhere like this.[br]Why don't we try another question?")
  GAME:WaitFrames(40)

  UI:WaitShowDialogue("Ugh, fine.")
  UI:WaitShowDialogue("Next question, and I'm gonna go straight to the point.")
  UI:WaitShowDialogue("Are you an explorer and/or do you have any relationship with one?")
  GAME:WaitFrames(70)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("...")
  UI:WaitShowDialogue('What are "Explorers"?')
  GAME:WaitFrames(90)

 
 
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Ha![pause=60] Listen to this guy!")
  
  UI:WaitShowDialogue("Do you really expect us to believe that you don't know what explorers are?")
  UI:WaitShowDialogue("Everyone knows about them!")
  UI:WaitShowDialogue("Even a baby knows what an explorer is!")
  UI:WaitShowDialogue(STRINGS:Format("You aren't fooling anyone, {0}.", player:GetDisplayName()))

  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("B-But it's true!") 
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("I don't know what an explorer is!")

  GAME:WaitFrames(80)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("...") 
  UI:WaitShowDialogue("Someone looked around the area right before we brought him here, right?")
  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("I did. There was nothing. Not a treasure bag or a badge.")
  UI:WaitShowDialogue("He's clean.")


  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("...") 
  UI:WaitShowDialogue("Ugh, fine!") 
  UI:WaitShowDialogue("Let's say, hypothetically, you were telling the truth and that you are really not an explorer and that you don't remember anything.") 
  UI:WaitShowDialogue("How and why would you be in the middle of a clearing at the end of a Mystery Dungeon, with no items or a way to communicate with anyone?") 
  GAME:WaitFrames(80)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("...") 
  UI:WaitShowDialogue("I don't know.") 
  GAME:WaitFrames(40)

  SOUND:PlayBattleSE("EVT_Battle_Flash")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(6)
  GAME:FadeIn(1)
 
  GAME:WaitFrames(40)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("That's not an answer!") 

  GAME:WaitFrames(80)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("...") 
  GAME:WaitFrames(50)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("...!") 
  GAME:WaitFrames(80)
    --He got pissed.

  UI:WaitShowDialogue("You want an answer?") 
  UI:WaitShowDialogue("How about I give you the same answer I've been giving you all this time?") 
  GAME:WaitFrames(10)
  SOUND:PlaySE("Battle/EVT_Emote_Complain_2")
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Who do you think you are to talk to him like that?") 
  GAME:WaitFrames(60)

  UI:WaitShowDialogue("HEY! [pause=60]Shut up!") 
  UI:WaitShowDialogue("What did I say about watching in silence?") 

  UI:WaitShowDialogue("...") 
  GAME:WaitFrames(70)

 
  UI:WaitShowDialogue(STRINGS:Format("Go on, {0}.", player:GetDisplayName())) 

  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Determined")

  UI:WaitShowDialogue("Look, I don't know what you expect me to tell you, but I'm sure that, whatever it is, you're not going to like it.") 
  UI:WaitShowDialogue("You want to know why I woke up in the middle of a clearing?") 
  UI:WaitShowDialogue("News flash! I do too!") 
  UI:WaitShowDialogue("But instead of finding out the reason I got turned into a Pokémon and thrown there, I get kidnapped by whatever the hell you guys are!") 
  UI:WaitShowDialogue("Police?[pause=0] Criminals?[pause=0] I don't give a damn!")
  UI:SetSpeakerEmotion("Teary-Eyed")
  UI:WaitShowDialogue("I had a family, you know?") 
  UI:WaitShowDialogue("And I know I will probably never see them again!") 
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("But I haven't even had time to dwell on it!") 
  UI:WaitShowDialogue("And you know why?[pause=0] Because I gotta answer your stupid questions while trying not to have a breakdown!") 

  GAME:WaitFrames(60)

  UI:WaitShowDialogue("So no,[pause=50] I don't know what I was doing in that clearing.")
  UI:WaitShowDialogue("I don't know what an explorer is.") 
  UI:WaitShowDialogue("And I definitely don't know what a Mystery Dungeon is!") 
  UI:WaitShowDialogue("And if you don't like the answers,[pause=40] too bad! [pause=60]Go cry about it, 'cus you're not getting anything else out of me!") 
  UI:WaitShowDialogue("You know why?") 
  GAME:WaitFrames(60)

  Hop(player, 'None', 10)
  Hop(player, 'None', 10, 10, false)

  UI:SetSpeakerEmotion("Shouting")
  UI:WaitShowDialogue("Because I have freaking amnesia![pause=0] Drill it into your brain already!") 
  GAME:WaitFrames(120)
  UI:ResetSpeaker()
  UI:WaitShowDialogue(".[pause=60].[pause=60].[pause=60]") 
  GAME:WaitFrames(80)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("...!") 
  UI:WaitShowDialogue("Shoot.") 
  GAME:WaitFrames(50)

  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Look, I'm-") 

  GROUND:CharSetEmote(player, "exclaim", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("[speed=0.7]Hahahahahahahahahaha!")
  GAME:WaitFrames(70)
  UI:WaitShowDialogue("You've got some gall to speak to us like that.") 

  UI:WaitShowDialogue(STRINGS:Format("I like you, {0}.", player:GetDisplayName()))
  UI:WaitShowDialogue("And it's not usual I say that to someone I'm interrogating.")
  GAME:WaitFrames(50)

  UI:WaitShowDialogue("I'm gonna tell the Boss about this.")
  UI:WaitShowDialogue("Partner,[pause=40] wanna make sure our friend here doesn't try to escape while I do that?")

  UI:WaitShowDialogue("Okay.")

  UI:WaitShowDialogue("You three, interrogation's done.")
  UI:WaitShowDialogue("Go back and do your regular stuff, or whatever.")

  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Can I stay?")
  UI:WaitShowDialogue("I think I should...[pause=60] talk to him.")

  GAME:WaitFrames(70)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Your choice.")
  UI:WaitShowDialogue("You have until I come back.")
  UI:WaitShowDialogue(STRINGS:Format("Make sure our friend {0} here doesn't try anything funny on the rookie.", player:GetDisplayName()))
  GAME:WaitFrames(50)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("Wouldn't dream of it.") 
  GAME:WaitFrames(70)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("You better.")
  UI:WaitShowDialogue("You can keep the illusion by yourself while I'm gone, right?")
  GAME:WaitFrames(50)
  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("(Illusion?)")
  GAME:WaitFrames(40)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Who do you take me for?")
  UI:WaitShowDialogue("Of course I can!")
  UI:WaitShowDialogue("Just don't do any big or sharp movements, okay rookie?")


  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("You should just focus on hiding yourself.")
  UI:WaitShowDialogue("No point in hiding me if he already knows I'm here.")
  UI:WaitShowDialogue("Plus, hiding yourself will probably be less tiring than hiding the room and us two.")
  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Newbie's giving you classes about your own ability?")
  GAME:WaitFrames(50)

  SOUND:PlaySE("Battle/EVT_Emote_Complain_2")
  UI:WaitShowDialogue("Weren't you supposed to be reporting to the Boss?")
  UI:WaitShowDialogue("Hehe. [pause=60]Alright, sweetie, I'll leave you and your teacher alone now.")
  UI:WaitShowDialogue("You two.[pause=40] Come on, let's go.")

  GAME:WaitFrames(140)
  UI:WaitShowDialogue("I still don't know how I put up with him sometimes...")
  UI:WaitShowDialogue("Anyway, back to our friend here.")
  UI:WaitShowDialogue(STRINGS:Format("{0}, was it?", player:GetDisplayName()))
  --]]
  UI:WaitShowDialogue("Prepare your eyes for a rather abrupt change in lightning.")
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("What does that mean?")

  GAME:WaitFrames(60)

  SOUND:PlayBattleSE('EVT_Battle_Transition')
  GAME:FadeOut(true, 120)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("AHHHH!")
  GROUND:Unhide('Partner')
  GROUND:Hide('Black_Stuff')
  UI:WaitShowDialogue("I can't see!")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("That's the point!")
  UI:WaitShowDialogue("Now, shut up and don't make me lose my focus!")
  GAME:WaitFrames(100)

  GAME:FadeIn(60)
  GAME:WaitFrames(80)
  GROUND:EntTurn(player, Direction.DownLeft)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.Left)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.UpLeft)
  GAME:WaitFrames(80)

  GROUND:EntTurn(player, Direction.Left)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.DownLeft)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.Down)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.DownRight)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.Right)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(80)
  GROUND:EntTurn(player, Direction.Right)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.DownRight)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.Down)
  GAME:WaitFrames(40)
  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(30)
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(80)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Dizzy")
  UI:WaitShowDialogue("Ugh, my eyes hurt...")
  GAME:WaitFrames(40)

  GROUND:EntTurn(player, Direction.DownRight)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.Down)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.DownLeft)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.Down)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.DownRight)
  GAME:WaitFrames(3)
  GROUND:EntTurn(player, Direction.Down)
  GAME:WaitFrames(90)

  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)

  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue(STRINGS:Format("Hello, {0}.", player:GetDisplayName()))
  GAME:WaitFrames(60)
  GROUND:EntTurn(player, Direction.DownLeft)
  GAME:WaitFrames(80)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("...")
  GAME:WaitFrames(60)

  UI:WaitShowDialogue("You...")
  UI:WaitShowDialogue("I trusted you.")

  GAME:WaitFrames(80)
  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("I know.")
  UI:WaitShowDialogue("I already told you I'm sorry before all of this happened.")

  GAME:WaitFrames(100)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("...")
  UI:WaitShowDialogue("Apologies not accepted.")

  GAME:WaitFrames(50)
  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Sigh")
  UI:WaitShowDialogue("I figured as much.")
  GAME:WaitFrames(70)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("What are you supposed to be?")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Police?")
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("I'm sure not.")
  GAME:WaitFrames(70)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Should I refresh your memories a little bit?")
  GAME:WaitFrames(50)
  GROUND:EntTurn(player, Direction.DownRight)
  GROUND:EntTurn(partner, Direction.Right)

  UI:WaitShowDialogue("We are the [color=#03f8fc]Thieves Guild[color].")
  UI:WaitShowDialogue("A lot less legal, but definitely much cooler than that boring [color=#03f8fc]Aggron's Guild[color] in [color=#fcacac]Twilight Town[color].")
  UI:WaitShowDialogue("We're quite well known among the townsfolk, if I may add, hehe.")
  UI:WaitShowDialogue("'Cus we don't just steal.")
  UI:WaitShowDialogue("We do a lot more than that.")

   
  GAME:WaitFrames(40)
  GROUND:CharSetEmote(player, "shock", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Shock')
  GAME:WaitFrames(100)

  UI:SetSpeaker(player)
  GROUND:EntTurn(partner, Direction.UpRight)

  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Th-[pause=60]Thieves?!")
  GAME:WaitFrames(40)

  GROUND:CharSetEmote(player, "sweating", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweating')
  GAME:WaitFrames(80)
  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("(What have I done to deserve this?)")
  UI:WaitShowDialogue("(Was I that bad of a person before I got here?)")

  
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Oh, where did all that confidance from before go?")
  UI:WaitShowDialogue("You better hope Boss's in a good mood today.")
  UI:WaitShowDialogue("No one knows where we are now.")
  UI:WaitShowDialogue("Getting rid of you could be...[pause=60] let's say,[pause=30] really easy.")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("...!")

  GAME:WaitFrames(50)
  GROUND:CharSetEmote(partner, "sweatdrop", 1)
  SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")

  GAME:WaitFrames(100)
  GROUND:EntTurn(partner, Direction.Up)
  GAME:WaitFrames(5)

  GROUND:EntTurn(partner, Direction.UpLeft)
  GAME:WaitFrames(5)
  GROUND:EntTurn(partner, Direction.Left)
  GAME:WaitFrames(5)
  GROUND:EntTurn(partner, Direction.DownLeft)

 
  GAME:WaitFrames(60)
  UI:SetSpeaker('', true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("(Hopefully [color=#03f8fc]Kit[color] will come back before she traumatizes him...)")


  GROUND:EntTurn(partner, Direction.Left)
  GAME:WaitFrames(5)
  GROUND:EntTurn(partner, Direction.UpLeft)
  GAME:WaitFrames(5)
  GROUND:EntTurn(partner, Direction.Up)
  GAME:WaitFrames(5)
  GROUND:EntTurn(partner, Direction.UpRight)

  GAME:WaitFrames(50)
  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue(STRINGS:Format("So...[pause=40] your name is actually {0},[pause=50] right?", player:GetDisplayName()))
  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("I don't know.")
  UI:WaitShowDialogue("It's the only name I could remember.")

  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Oh.")
  UI:WaitShowDialogue("Well, it's...[pause=50] cool, I guess?")

  GAME:WaitFrames(60)
  GROUND:EntTurn(player, Direction.DownLeft)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("What's yours?")

  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Well,[pause=80] I don't[pause=40] have one?")
  UI:SetSpeakerEmotion("Sad")
  UI:WaitShowDialogue("My parents never gave me one.")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("And I never had the need to have one until very recently, so I'm still deciding.")
  
  GAME:WaitFrames(50)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Your parents...[pause=50] never gave you one?")
  GAME:WaitFrames(40)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("It's none of your business, "..player:GetDisplayName()..".")
  GAME:WaitFrames(70)


  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("...")

  GAME:WaitFrames(60)

  GROUND:Unhide('Kit')
  local kit = CH('Kit')
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
  GROUND:EntTurn(player, Direction.Down)
  local coro1 = TASK:BranchCoroutine(function() interrogation.THETurnFunction(partner, "down") end)
  local coro2 = TASK:BranchCoroutine(function() interrogation.THEEmoteFunction(partner, "exclaim") end)
  local coro3 = TASK:BranchCoroutine(function() interrogation.THEEmoteFunction(player, "exclaim") end)
  local coro4 = TASK:BranchCoroutine(function() interrogation.THEMoveFunction(kit, "up") end)

  TASK:JoinCoroutines({coro1,coro2,coro3,coro4})

  GAME:WaitFrames(70)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("'Sup![pause=0] I'm back.")
  GAME:WaitFrames(50)


  GROUND:CharSetEmote(player, "exclaim", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')

  GAME:WaitFrames(80)

  UI:SetSpeaker("", true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("(A [color=#07e015]Zoroark[color]!)")
  UI:WaitShowDialogue("(That's why I couldn't see anything!)")
  UI:WaitShowDialogue("(It was an illusion!)")
  GAME:WaitFrames(80)




  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("What are you doing?!")
  UI:WaitShowDialogue("Hide yourself!")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Nah.")
  UI:WaitShowDialogue("That' won't be necessary.")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("In fact, you shouldn't waste energy in yourself anymore.")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("What do you mean?")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Yeah, what does that mean?")
  GAME:WaitFrames(70)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue(STRINGS:Format("I've talked to the Boss about {0} and his supposed amnesia and null affiliation with any explorers.", player:GetDisplayName()))
  UI:WaitShowDialogue("Long story short, she still doesn't buy it.")


  GROUND:CharSetEmote(player, "angry", 2)
  SOUND:PlaySE("Battle/EVT_Emote_Complain_2")
  Hop(player, 'None', 10)
  Hop(player, 'None', 10)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("What do you mean she doesn't buy it?!")

  GROUND:EntTurn(partner, Direction.UpRight)
    
  interrogation.Ouchie(player)

    

 

  GAME:WaitFrames(60)
  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(30)
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(80)

  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("OW!")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue(STRINGS:Format("Keep quiet, {0}.", player:GetDisplayName()))
  UI:WaitShowDialogue("Go on.")
  interrogation.THETurnFunction(partner,"down2")
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("As I was saying, Boss doesn't buy it.")
  UI:WaitShowDialogue("[speed=0.3]Aaaaand [speed=1]since we have no experienced enough psychic types around here, we have no reliable way to know if he's lying or not.")

  GAME:WaitFrames(80)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("How does that have anything to do with you not being hidden?")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("I was getting to that!")

  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue(STRINGS:Format("{0}, get up.", player:GetDisplayName()))
  UI:WaitShowDialogue("This concerns you.")
  UI:WaitShowDialogue("A lot, in fact.")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Can I...[pause=60] Can I get a moment?")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Nope!")
  UI:WaitShowDialogue("On your feet.")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("...")
  UI:WaitShowDialogue("Fine...")

  GAME:WaitFrames(30)

  GROUND:CharSetAnim(player, "Wake", false)

  GAME:WaitFrames(90)
  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(30)
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(80)

  UI:WaitShowDialogue("I think something is broken...")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("You're a fighting type. [pause=0]Your bones won't break because of some blows.")
  UI:WaitShowDialogue("What a crybaby.")
  GAME:WaitFrames(60)


  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue(STRINGS:Format("Alright, {0}. Going back to what I said before, we are going to assume everything you told us is a lie.", player:GetDisplayName()))


  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("But it's not-!")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("I'm not done.")
  GAME:WaitFrames(90)

  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("As I was saying, as far as the Boss is concerned, nothing you've said is true.")
  UI:WaitShowDialogue("And you know a little too much about us to just let you go.")
  GAME:WaitFrames(60)
 
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("I don't like where this is going...")
  GAME:WaitFrames(50)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Great!")
  UI:WaitShowDialogue("That's exactly the point!")
  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Now, Boss gave you two options, you can choose whatever you seem more fit.")

  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Which options are they?")

  GAME:WaitFrames(80)
  
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Well, the first one is of course the easy one for us.")
  GAME:WaitFrames(80)

  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("We simply get rid of you.")

  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Throw you off a cliff or something.")
  UI:WaitShowDialogue("I dunno how Boss deals with those things.")
  GAME:WaitFrames(80)

  GROUND:CharSetEmote(player, "shock", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Shock')
  GAME:WaitFrames(70)

  SOUND:PlayBGM("Growing Anxiety.ogg", true) 
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Excuse me?!")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  GROUND:EntTurn(player, Direction.DownRight)
  GROUND:EntTurn(partner, Direction.Right)

  UI:WaitShowDialogue("I like that idea.")
  UI:WaitShowDialogue("Nice and easy.")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("What?")
  GAME:WaitFrames(50)
  GROUND:CharSetEmote(partner, "sweatdrop", 1)
  SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
  GAME:WaitFrames(100)
  UI:SetSpeaker('', true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("([color=#00ff00]Arceus[color], what have I done?)")
  GAME:WaitFrames(70)

  GROUND:EntTurn(partner, Direction.DownRight)
  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("What's...[pause=60] the other option?")
  GAME:WaitFrames(50)
  GROUND:EntTurn(kit, Direction.UpLeft)

  GAME:WaitFrames(30)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("What's wrong, newbie?")
  UI:WaitShowDialogue(STRINGS:Format("I thought you and {0} were on bad terms?", player:GetDisplayName()))
  UI:WaitShowDialogue("Why the sudden change?")
  
  --GROUND:EntTurn(partner, Direction.DownRight)
  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Well, I mean...")
  UI:WaitShowDialogue("Shouldn't we at least listen to the other option before choosing?")
  GAME:WaitFrames(50)

  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)

  UI:SetSpeaker(player)
  GROUND:EntTurn(player, Direction.Down)

  UI:SetSpeakerEmotion("Teary-Eyed")
  UI:WaitShowDialogue("I don't want to die...")
  UI:WaitShowDialogue("P-[pause=50]Please...")

  GAME:WaitFrames(80)
  SOUND:FadeOutBGM(80)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("...")
  GAME:WaitFrames(70)

  GROUND:EntTurn(kit, Direction.Up)
  UI:WaitShowDialogue(STRINGS:Format("Come on, {0}.", player:GetDisplayName()))
  
  UI:WaitShowDialogue("We are criminals, not monsters.")
  UI:WaitShowDialogue("If we say we are giving you two options to choose, we will give you two options.")

  GAME:WaitFrames(60)
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Teary-Eyed")
  UI:WaitShowDialogue("...")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Anyway,[pause=50] the second options is a bit harder for everyone, and will requiere you get put through a test, [pause=60]but if you pass it, you can keep living.")
  GAME:WaitFrames(60)

  UI:SetSpeaker("[color=#fff30a]Sprigatito[color]", true, partner.CurrentForm.Species, partner.CurrentForm.Form, partner.CurrentForm.Skin, partner.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Wait,[pause=60] you don't mean...")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Yup.")
  UI:WaitShowDialogue("Despite what you may think, Boss doesn't like to just get rid of Pokémon without any reason.")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("She says that if the explorers know you just disappeared without explanation, they will send stronger 'mons to search for you and all that.")
 


  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Get to the point.")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Determined")

  GROUND:EntTurn(kit, Direction.UpRight)
  

  UI:WaitShowDialogue("Geez, you're in a hurry today, huh?")
  GAME:WaitFrames(40)
  GROUND:EntTurn(kit, Direction.Up)
  GAME:WaitFrames(20)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue(STRINGS:Format("{0}, do you have any idea what the proposal could be about?", player:GetDisplayName()))
  GAME:WaitFrames(60)
  UI:SetSpeaker(player)

  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("...")
  GAME:WaitFrames(60)
  UI:WaitShowDialogue("No?")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Well,[pause=40] doesn't matter!")

  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Boss gave you the chance to join us here in the guild.")
  
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Since,[pause=40] according to her,[pause=40] you lied about not being an explorer,[pause=50] you have to have some skills that could prove to be useful to us.")
  UI:WaitShowDialogue("And that's why those abilities are going to be put to the test.")
 
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("So pass it, and you can become one of us!")
  GAME:WaitFrames(40)
  GROUND:CharSetEmote(player, "sweating", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweating')
  GAME:WaitFrames(120)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("What?[pause=0] Join the guild?")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("But... [pause=60]wouldn't I have to become a thief too?")
  GAME:WaitFrames(40)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Duh!")
  
  GROUND:EntTurn(player, Direction.DownRight)
  GROUND:EntTurn(partner, Direction.Right)


  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("This is the [color=#03f8fc]Thieves Guild[color], not the Love and Hugs Guild.")
  GAME:WaitFrames(100)
  GROUND:EntTurn(player, Direction.Down)
  GROUND:EntTurn(player, Direction.DownRight)
  
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("But I'm...")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Not cut out to be a thief?")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Quite an amount of members thought and still think the same.")
  UI:WaitShowDialogue("Members that couldn't find any other source of money have to resort to joining us, and even if they think they can't help, some of them are one of the most valuable members here.")
  GAME:WaitFrames(60)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("No other source of money?")
  GAME:WaitFrames(50)
  GROUND:EntTurn(player, Direction.DownRight)
  GROUND:EntTurn(partner, Direction.Right)
  GROUND:EntTurn(kit, Direction.UpRight)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Yup.")
  UI:WaitShowDialogue("There aren't a lot of those around here, and the rotten 'mons that run the only ones that exist make it too difficult to get even the slightest bit of money from them.")
  UI:WaitShowDialogue("Everyone wants to join [color=#03f8fc]Aggron's Guild[color], but do you know how many teams there are there?")
  UI:WaitShowDialogue("Not half of what we have here!")
  UI:WaitShowDialogue('And even if you have the "luck" to join, they will take almost all of the money you earn!')
  UI:WaitShowDialogue("That's a scam, if I've ever seen one!")
  UI:WaitShowDialogue("At least here you can keep half of the money instead of the 10% you'd have with them!")
  GAME:WaitFrames(80)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("10%?!")
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("That's the only amount they keep?")

  GROUND:EntTurn(player, Direction.Down)
  GROUND:EntTurn(partner, Direction.DownRight)
  GROUND:EntTurn(kit, Direction.Up)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:WaitShowDialogue("I know it's sad.")
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Me and my partner learnt that the hard way.")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("You've been in there?")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Sad")
  UI:WaitShowDialogue("Long before I joined here.")
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("They were the hardest three weeks of our whole life...")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Thankfully, one day we found the Boss and she showed us this guild.")
  UI:WaitShowDialogue("Now we are one of the oldest team around here.")
  GAME:WaitFrames(60)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue(STRINGS:Format("Sorry to interrupt the storytelling, but {0} has to give us an answer yet.", player:GetDisplayName()))
  GAME:WaitFrames(80)
  UI:WaitShowDialogue("What will it be?")
  UI:WaitShowDialogue("Will you try your luck with the test?")
  GAME:WaitFrames(80)

  UI:SetSpeaker(player)
  GROUND:EntTurn(partner, Direction.UpRight)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("What happens if I fail the test?")
  GAME:WaitFrames(120)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Well...")
  UI:WaitShowDialogue("Probably the same as the first option.")
  UI:WaitShowDialogue("Boss won't want a useless member.")
  GAME:WaitFrames(60)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("So either I join, or I die?")
  UI:WaitShowDialogue("Is that it?")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Apparently so.")
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue(STRINGS:Format("So what will it be, {0}?", player:GetDisplayName()))
  GAME:WaitFrames(60)

  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("(Why?)")
  UI:WaitShowDialogue("(What did I do to deserve this?)")
  UI:WaitShowDialogue("(Can I really keep up a life being a criminal?)")
  GAME:WaitFrames(70)
  UI:WaitShowDialogue("(I'll die if I don't.)")
  UI:WaitShowDialogue("(I'm so sorry, morals...)")
  GAME:WaitFrames(60)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("Bring it on!")

  GROUND:EntTurn(partner, Direction.DownRight)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, kit.CurrentForm.Species, kit.CurrentForm.Form, kit.CurrentForm.Skin, kit.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Determined, I see!")

  GROUND:EntTurn(kit, Direction.UpRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(kit, Direction.Right)
  GAME:WaitFrames(5)
  GROUND:EntTurn(kit, Direction.DownRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(kit, Direction.Down)
  GAME:WaitFrames(60)

  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("Now, try not to get another case of amnesia again.")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("What-?")

  GAME:FadeOut(false, 1)
  SOUND:PlaySE("Battle/DUN_Tackle")

  
  GAME:CutsceneMode(false)
  GAME:EnterZone('thieves_hideout', -1, 2, 0)

end

function interrogation.Ouchie(char)
  SOUND:PlayBattleSE("EVT_Battle_Flash")
  GAME:FadeOut(true, 1)
  GROUND:CharSetAction(char, RogueEssence.Ground.PoseGroundAction(char.Position, char.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pain")))
  GAME:WaitFrames(6)
  GAME:FadeIn(1)



end
function interrogation.THETurnFunction(char, todo)
  if todo == 'down' then
    GROUND:EntTurn(char, Direction.Right)
    GAME:WaitFrames(3)
    GROUND:EntTurn(char, Direction.DownRight)
    GAME:WaitFrames(3)
    GROUND:EntTurn(char, Direction.Down)
    GAME:WaitFrames(35)
    GROUND:EntTurn(char, Direction.DownRight)

  elseif todo == 'up' then
    GROUND:EntTurn(char, Direction.Right)
    GAME:WaitFrames(3)
    GROUND:EntTurn(char, Direction.UpRight)
  elseif todo == 'down2' then
    
    GROUND:EntTurn(char, Direction.Right)
    GAME:WaitFrames(3)
    GROUND:EntTurn(char, Direction.DownRight)

  end


end
function interrogation.THEEmoteFunction(char, emote)
  GROUND:CharSetEmote(char, emote, 1)

end
function interrogation.THEMoveFunction(char, todo)
  if todo == 'up' then
    GROUND:MoveInDirection(char, Direction.Up, 60, false, 2)
  end
end



function Hop(chara, anim, height, duration, pause, sound)
  anim = anim or 'None'
  height = height or 10
  duration = duration or 10
  if pause == nil then pause = true end
  if sound == nil then sound = false end

  local animId = RogueEssence.Content.GraphicsManager.GetAnimIndex(anim)
  GROUND:CharSetAction(chara, RogueEssence.Ground.HopGroundAction(chara.Position, chara.Direction, animId, height, duration))
  
  if sound then
   SOUND:PlayBattleSE("EVT_Emote_Startled")
  end
  
  if pause then 
    GAME:WaitFrames(duration)
  end

end
---interrogation.Exit(map)
--Engine callback function
function interrogation.Exit(map)


end

---interrogation.Update(map)
--Engine callback function
function interrogation.Update(map)


end

---interrogation.GameSave(map)
--Engine callback function
function interrogation.GameSave(map)


end

---interrogation.GameLoad(map)
--Engine callback function
function interrogation.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks         |
-------------------------------


return interrogation

