--[[
    init.lua
    Created: 05/02/2024 10:21:11
    Description: Autogenerated script file for the map room_kiran_and_lucio.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local room_kiran_and_lucio = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---room_kiran_and_lucio.Init(map)
--Engine callback function
function room_kiran_and_lucio.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies()
  local partners = CH('Teammate1')
  AI:SetCharacterAI(partners, "ai.ground_partner", CH('PLAYER'), partners.Position)
  AI:EnableCharacterAI(partners)
  partners.CollisionDisabled = true
  local sleepyhead = CH('Lucio')
  if not SV.guildmasters_office.officially_joined then
    GROUND:CharSetAnim(sleepyhead, "Sleep", true)


  else
    GROUND:Hide('Kiran')
    GROUND:Hide('Lucio')

  end

end

---room_kiran_and_lucio.Enter(map)
--Engine callback function
function room_kiran_and_lucio.Enter(map)

  GAME:FadeIn(20)

end

---room_kiran_and_lucio.Exit(map)
--Engine callback function
function room_kiran_and_lucio.Exit(map)


end

---room_kiran_and_lucio.Update(map)
--Engine callback function
function room_kiran_and_lucio.Update(map)


end

---room_kiran_and_lucio.GameSave(map)
--Engine callback function
  function room_kiran_and_lucio.GameSave(map)
    local partner = CH('Teammate1')
    SV.partner.positionX = partner.Position.X
    SV.partner.positionY = partner.Position.Y
    SV.partner.direction = DirToNum(partner.Direction)
  
  end
  
  ---room_lily_and_celia.GameLoad(map)
  --Engine callback function
  function room_kiran_and_lucio.GameLoad(map)
  
    local partners = CH('Teammate1')
    GROUND:TeleportTo(partners, SV.partner.positionX, SV.partner.positionY, NumToDir(SV.partner.direction))
    
  
    AI:SetCharacterAI(partners, "ai.ground_partner", CH('PLAYER'), partners.Position)
    AI:EnableCharacterAI(partners)
    partners.CollisionDisabled = true
    
    GAME:FadeIn(20)
  
  end
  function Dialogue(sp, state, emote, txt)
    if state == 0 then --Speaker is unknown and invisible
      UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
    elseif state == 1 then --Speaker is unknown, but visible (AKA, you don't know their name)
      UI:SetSpeaker(STRINGS:Format("\\uE040"), true, sp.CurrentForm.Species, sp.CurrentForm.Form, sp.CurrentForm.Skin, sp.CurrentForm.Gender)
    elseif state == 2 then --Speaker is thinking to themselves. (Parenthesis are NOT included here.)
      UI:SetSpeaker("", true, sp.CurrentForm.Species, sp.CurrentForm.Form, sp.CurrentForm.Skin, sp.CurrentForm.Gender)
    else --Speaker speaks regularly
      UI:SetSpeaker(sp)
    end
    UI:SetSpeakerEmotion(emote)
    UI:WaitShowDialogue(txt)
  
  
  end
  
  function DirToNum(dir)
    --up is 0, upright is 1, ... up left is 7
    local num = -1
    if dir == Direction.Up then
      num = 0
    elseif dir == Direction.UpRight then
      num = 1
    elseif dir == Direction.Right then
      num = 2
    elseif dir == Direction.DownRight then
      num = 3
    elseif dir == Direction.Down then
      num = 4
    elseif dir == Direction.DownLeft then
      num = 5
    elseif dir == Direction.Left then
      num = 6
    elseif dir == Direction.UpLeft then
      num = 7
    end
    
    return num
    
  end
  --converts a number to a direction
  function NumToDir(num)
    local dir = Direction.None
    if num % 8 == 0 then 
      dir = Direction.Up
    elseif num % 8 == 1 then
      dir = Direction.UpRight
    elseif num % 8 == 2 then
      dir = Direction.Right
    elseif num % 8 == 3 then
      dir = Direction.DownRight
    elseif num % 8 == 4 then
      dir = Direction.Down
    elseif num % 8 == 5 then
      dir = Direction.DownLeft
    elseif num % 8 == 6 then
      dir = Direction.Left
    elseif num % 8 == 7 then
      dir = Direction.UpLeft
    end
  
    return dir
  end 
-------------------------------
-- Entities Callbacks
-------------------------------
function room_kiran_and_lucio.exit_Touch(obj, activator)
  GAME:FadeOut(false, 20)

  SV.partner.entrance = 3
  GAME:EnterZone('thieves_hideout', -1, 11, 5)

end
function room_kiran_and_lucio.Kiran_Action(obj, activator)
  local kiran = obj
  local player = activator
  local partner = CH("Teammate1")
  local lucio = CH("Lucio")

  if not SV.guild.presented_to_overcharge then
    GAME:FadeOut(false, 20)
    GAME:CutsceneMode(true)
    AI:DisableCharacterAI(partner)
    GROUND:CharTurnToChar(partner, kiran)
   
    local marker = MRKR('me')
		GROUND:TeleportTo(player, marker.Position.X, marker.Position.Y, marker.Direction)
    local marker2 = MRKR('part')
		GROUND:TeleportTo(partner, marker2.Position.X, marker2.Position.Y, marker2.Direction)
    GROUND:CharSetAnim(lucio, "Sleep", true)
    GAME:WaitFrames(60)

    GAME:FadeIn(20)
    GAME:WaitFrames(60)
    Dialogue(kiran, 3, "Normal", "Just gotta set this on fire...")
    SOUND:PlaySE('Battle/EVT_Emote_Exclaim')
		GROUND:CharSetEmote(kiran, "notice", 1)
    GAME:WaitFrames(80)
    GROUND:CharTurnToCharAnimated(kiran, player, 5)
    GAME:WaitFrames(50)
    GROUND:CharTurnToCharAnimated(kiran, partner, 5)
    GAME:WaitFrames(50)
    GROUND:CharTurnToCharAnimated(kiran, player, 5)
    Dialogue(kiran, 3, "Happy", "Oh, hi there ".. player:GetDisplayName() .. " and ".. partner:GetDisplayName().."!")
    Dialogue(kiran, 3, "Happy", "How was the rest of the meeting with [color=#00ffff]Ma'am[color]?[br]Did you get everything sorted out?")
    GROUND:CharTurnToCharAnimated(kiran, partner, 4)
    
    Dialogue(partner, 3, "Happy", "It went pretty good!")
    Dialogue(partner, 3, "Normal", player:GetDisplayName().." and me are now a team!")
    Dialogue(partner, 3, "Happy", "Team " ..GAME:GetTeamName().."!")
    Dialogue(partner, 3, "Happy", "He picked the name!")
    GAME:WaitFrames(60)
    Dialogue(kiran, 3, "Happy", "That's a dope team name![br]I knew you two would end up together![pause=30] You really make a great team.")
    
    GROUND:CharTurnToCharAnimated(player, lucio, 4)
    GAME:WaitFrames(50)
    GROUND:CharTurnToCharAnimated(player, kiran, 4)
    GAME:WaitFrames(70)
    GROUND:CharTurnToCharAnimated(kiran, player, 4)

    Dialogue(player, 3, "Worried", "Did your brother fall asleep already?")
    GROUND:CharTurnToCharAnimated(partner, lucio, 4)
    GAME:WaitFrames(60)
    SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
		GROUND:CharSetEmote(partner, "exclaim", 1)
    Dialogue(partner, 3, "Surprised", "I hadn't even realized!")
    GROUND:CharTurnToCharAnimated(kiran, partner, 5)

    Dialogue(kiran, 3, "Happy", "Yeah, that's just my brother!")
    GROUND:CharTurnToCharAnimated(partner, kiran, 4)
    Dialogue(kiran, 3, "Normal", "He said that he wanted to share stories with me over the fire once I arrived here, but when I turned around to start it, he was already snoozing!")
    Dialogue(kiran, 3, "Happy", "Today was extra tiring for someone, it seems!")
    GAME:WaitFrames(60)
    Dialogue(partner, 3, "Worried", "Well, today's operation was your first one...[pause=40] And then you had to fight us, so I suppose it makes sense.")
    Dialogue(kiran, 3, "Worried", "Yeah, today was tiring...")
    Dialogue(kiran, 3, "Happy", "That's why I'll have to make sure to sleep well tonight.")
    GROUND:CharTurnToCharAnimated(kiran, partner, 4)

    GAME:WaitFrames(15)
    Dialogue(kiran, 3, "Stunned", "Oh, and "..partner:GetDisplayName().."!")


    GROUND:CharTurnToCharAnimated(partner, kiran, 4)

    GAME:WaitFrames(15)
    Dialogue(partner, 3, "Normal", "Yeah?")
    Dialogue(kiran, 3, "Sad", "I'm sorry for having talked to you like that earlier.[br]I wasn't thinking straight.[pause=0] I know that the cops appearing wasn't your fault.")
    Dialogue(partner, 3, "Happy", "Oh, don't worry about it![br]Everyone was on edge, so I know yo didn't really mean it.")
    GAME:WaitFrames(50)
    GROUND:CharTurnToCharAnimated(player, partner, 4)

    Dialogue(player, 3, "Worried", "Am I missing something?")
    GROUND:CharTurnToCharAnimated(partner, player, 4)
    Dialogue(partner, 3, "Normal", "Don't worry about it.[pause=0] It's something we were doing before we found you.")
    Dialogue(player, 3, "Normal", "Oh...")
    GAME:WaitFrames(60)
    GROUND:CharTurnToCharAnimated(player, kiran, 4)
    GROUND:CharTurnToCharAnimated(partner, kiran, 4)

    Dialogue(kiran, 3, "Normal", "Well, thanks for coming, but I think I'm gonna go to sleep too.")
    Dialogue(kiran, 3, "Pain", "If I manage to start a fire, that is...")

    Dialogue(partner, 3, "Normal", "Got it.[br]We'll leave you two alone.")

    Dialogue(kiran, 3, "Happy", "Thank you!")
    Dialogue(kiran, 3, "Normal", "See you tomorrow!")
    
    GROUND:EntTurn(kiran, Direction.Right)

    AI:SetCharacterAI(partner, "ai.ground_partner", CH('PLAYER'), partner.Position)
    AI:EnableCharacterAI(partner)
    partner.CollisionDisabled = true
    SV.guild.presented_to_overcharge = true
    GAME:CutsceneMode(false)

  else
    Dialogue(kiran, 3, "Determined", "Just...[pause=40] start...[pause=40] the fire...[pause=40] already!")
    

  end
end

return room_kiran_and_lucio