--[[
    init.lua
    Created: 06/04/2024 12:34:44
    Description: Autogenerated script file for the map peaceful_lake.
]]--
-- Commonly included lua functions and data
require 'common'
require 'CommonFunctions'
require 'ground.peaceful_lake.peaceful_lake_ch2'
-- Package name
local peaceful_lake = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---peaceful_lake.Init(map)
--Engine callback function
function peaceful_lake.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies()
  local partners = CH('Teammate1')
  AI:SetCharacterAI(partners, "ai.ground_partner", CH('PLAYER'), partners.Position)
  AI:EnableCharacterAI(partners)
  partners.CollisionDisabled = true
end

---peaceful_lake.Enter(map)
--Engine callback function
function peaceful_lake.Enter(map)
  if SV.progression.chapter == 2 then
    if not SV.progression.first_day_done then
      peaceful_lake_ch.firstLakeIntro()

    end
  else
    GAME:FadeIn(20)


  end

end

---peaceful_lake.Exit(map)
--Engine callback function
function peaceful_lake.Exit(map)


end

---peaceful_lake.Update(map)
--Engine callback function
function peaceful_lake.Update(map)


end

---peaceful_lake.GameSave(map)
--Engine callback function
function peaceful_lake.GameSave(map)
  local partner = CH('Teammate1')
  SV.partner.positionX = partner.Position.X
	SV.partner.positionY = partner.Position.Y
	SV.partner.direction = DirToNum(partner.Direction)
end

---peaceful_lake.GameLoad(map)
--Engine callback function
function peaceful_lake.GameLoad(map)
  local partners = CH('Teammate1')
  AI:DisableCharacterAI(partners)
  GROUND:TeleportTo(partners, SV.partner.positionX, SV.partner.positionY, NumToDir(SV.partner.direction))
  

	AI:SetCharacterAI(partners, "ai.ground_partner", CH('PLAYER'), partners.Position)
  AI:EnableCharacterAI(partners)
  GAME:FadeIn(20)

end
function DirToNum(dir)
	--up is 0, upright is 1, ... up left is 7
	local num = -1
	if dir == Direction.Up then
		num = 0
	elseif dir == Direction.UpRight then
		num = 1
	elseif dir == Direction.Right then
		num = 2
	elseif dir == Direction.DownRight then
		num = 3
	elseif dir == Direction.Down then
		num = 4
	elseif dir == Direction.DownLeft then
		num = 5
	elseif dir == Direction.Left then
		num = 6
	elseif dir == Direction.UpLeft then
		num = 7
	end
	
	return num
	
end
--converts a number to a direction
function NumToDir(num)
	local dir = Direction.None
	if num % 8 == 0 then 
		dir = Direction.Up
	elseif num % 8 == 1 then
		dir = Direction.UpRight
	elseif num % 8 == 2 then
		dir = Direction.Right
	elseif num % 8 == 3 then
		dir = Direction.DownRight
	elseif num % 8 == 4 then
		dir = Direction.Down
	elseif num % 8 == 5 then
		dir = Direction.DownLeft
	elseif num % 8 == 6 then
		dir = Direction.Left
	elseif num % 8 == 7 then
		dir = Direction.UpLeft
	end

	return dir
end 
-------------------------------
-- Entities Callbacks
-------------------------------
function peaceful_lake.exit_Touch(obj, activator)
  SV.partner.entrance = 2
	GAME:FadeOut(false, 20)
  GAME:EnterZone('thieves_hideout', -1, 2, 0)
end

return peaceful_lake

