 --[[
    init.lua
    Created: 12/28/2023 12:23:00
    Description: Autogenerated script file for the map concealing_clearing.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local concealing_clearing = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---concealing_clearing.Init(map)
--Engine callback function
function concealing_clearing.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---concealing_clearing.Enter(map)
--Engine callback function
function concealing_clearing.Enter(map)
  UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 50)
  GAME:WaitFrames(50)
  UI:WaitHideTitle(50)
  GAME:CutsceneMode(true)
  SOUND:PlayBGM("In the Depths of the Pit.ogg", true) 
  if SV.conceal_forest_entrance.found_player == false then
    findPlayer()
  elseif SV.conceal_forest_entrance.found_player == true then
    GROUND:Hide('Fainted_Player')
    GROUND:Hide('Jacques')
    GROUND:Hide('Boss')
    --Regular "you reached the end of the dungeon cutscene"
  end
  
    
 






end
function findPlayer()

  local player = CH('PLAYER')
  local riolu = CH('Fainted_Player')
  local boss = CH('Boss')
  local thievul = CH('Jacques')
   GROUND:Hide('Boss')
   GROUND:Hide('Jacques')
  GAME:MoveCamera(192, 225, 1, false)
  GAME:FadeIn(20)
  GAME:WaitFrames(60)
  GROUND:MoveInDirection(player, Direction.Up, 140, false, 1.5)
  GROUND:CharSetAction(riolu, RogueEssence.Ground.PoseGroundAction(riolu.Position, riolu.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Laying")))

  
  GROUND:EntTurn(player, Direction.Left)
  GAME:WaitFrames(50)
  GROUND:EntTurn(player, Direction.UpLeft)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Up)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Right)
  GAME:WaitFrames(60)
  GROUND:CharSetEmote(player, "sweatdrop", 1)
  SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
  GAME:WaitFrames(80)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Ugh...")
  UI:WaitShowDialogue("Where even am I?")
  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("I think I got out of the dungeon, but...")
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Being lost in the forest isn't any better.")
  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Happy")
  GROUND:CharSetEmote(player, "happy", 0)
  UI:WaitShowDialogue("Well, at least there are no ferals here!")
  GROUND:CharSetEmote(player, "happy", 1)
  GAME:WaitFrames(100)
  UI:SetSpeakerEmotion("Sad")
  UI:WaitShowDialogue("What do I do now?")
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Going back inside the dungeon would only make me even more lost, and just walking forward won't cut it either...")
  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Ugh, do I just wait for someone to come get me?")
  UI:WaitShowDialogue("But there's no way to know for sure if anyone will stumble upon this clearing...")
  GAME:WaitFrames(60)
  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Ugh...[pause=40] What can I do?")
  SOUND:FadeOutBGM(80)
  GAME:WaitFrames(30)

  GROUND:CharSetEmote(player, "exclaim", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Groan...")

  GAME:WaitFrames(15)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Huh?")
  UI:WaitShowDialogue("What was that?")
  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Up)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.UpLeft)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Left)
  GAME:WaitFrames(60)
  GROUND:EntTurn(player, Direction.UpLeft)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Up)


  GAME:WaitFrames(120)
  GROUND:CharSetEmote(player, "shock", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Shock')

  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Wait, that's a-!")

  local coro1 = TASK:BranchCoroutine(function() concealing_clearing.moveCamera(192, 115, 60) end)
  local coro2 = TASK:BranchCoroutine(function() concealing_clearing.moveUp(player, 30, true, 4) end)
  TASK:JoinCoroutines({coro1,coro2})

  GAME:WaitFrames(40)
  SOUND:PlayBGM("In the Depths of the Pit.ogg", true) 
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("A [color=#00ff00]Riolu[color]!")
  UI:WaitShowDialogue("What are they doing here?")

  GAME:WaitFrames(70)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Wait...")

  GROUND:AnimateInDirection(player, "Walk", Direction.Up, Direction.Down, 5, 3, 2)

  GAME:WaitFrames(50)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("I shouldn't even be near them...")
  UI:WaitShowDialogue("What if they're an explorer?")
  UI:WaitShowDialogue("I could get in serious trouble if they realize I'm an outlaw...")
  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("But...")


  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("I can't just leave them like this!")


  GROUND:CharSetEmote(player, "exclaim", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
  GROUND:CharSetDrawEffect(riolu, DrawEffect.Trembling)
  GAME:WaitFrames(20)
  GROUND:CharEndDrawEffect(riolu, DrawEffect.Trembling)
  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Ugh...")
  UI:WaitShowDialogue("Where...?[pause=0] Who...?")

  GROUND:CharSetEmote(player, "shock", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Shock')
  GAME:WaitFrames(50)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Ahh! [pause=0]You're awake!")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("What?!")
  GROUND:CharSetAnim(riolu, "Wake", false)
  GAME:WaitFrames(60)
  GROUND:EntTurn(riolu, Direction.DownLeft)
  GAME:WaitFrames(5)
  GROUND:EntTurn(riolu, Direction.Left)
  GAME:WaitFrames(40)
  GROUND:EntTurn(riolu, Direction.DownLeft)
  GAME:WaitFrames(3)
  GROUND:EntTurn(riolu, Direction.Down)
  GAME:WaitFrames(3)
  GROUND:EntTurn(riolu, Direction.DownRight)
  GAME:WaitFrames(3)
  GROUND:EntTurn(riolu, Direction.Right)
  GAME:WaitFrames(40)
  GROUND:EntTurn(riolu, Direction.DownRight)
  GAME:WaitFrames(3)
  GROUND:EntTurn(riolu, Direction.Down)
  GAME:WaitFrames(60)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Where am I?")

  GROUND:CharSetDrawEffect(riolu, DrawEffect.Trembling)
  GAME:WaitFrames(20)
  GROUND:CharEndDrawEffect(riolu, DrawEffect.Trembling)
  GAME:WaitFrames(80)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Ow, my whole body hurts...")
  GAME:WaitFrames(60)


  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Erm...")
  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Hi?")
  GAME:WaitFrames(80)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Who are you?")
  GAME:WaitFrames(70)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("I could ask the same about you...")

  GAME:WaitFrames(30)
  GROUND:CharSetEmote(player, "exclaim", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')

  GAME:WaitFrames(60)

  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("(He doesn't know about me?)")

  UI:SetSpeakerEmotion("Sigh")
  UI:WaitShowDialogue("(Thank [color=#00ff00]Arceus[color]...)")
  UI:WaitShowDialogue("(I'm safe,[pause=30] for now)")
  GAME:WaitFrames(60)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Well, it desn't matter if you don't know.")
  UI:WaitShowDialogue("Are you okay?")
  UI:WaitShowDialogue("I found you laying on the ground, unconscious.")
  UI:WaitShowDialogue("I was worried something really bad hapened to you...")
  GAME:WaitFrames(30)
  
  UI:WaitShowDialogue("Are you sure you are not hurt?")
  UI:WaitShowDialogue("Did a feral get to you?")
  GAME:WaitFrames(60)
  UI:WaitShowDialogue("You don't look like that could have happened, but just to be sure...")
  SOUND:FadeOutBGM(100)
  GAME:WaitFrames(60)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("A...[pause=60] feral?")

  GAME:WaitFrames(50)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Umm...")
  UI:WaitShowDialogue("Yeah?")
  UI:WaitShowDialogue("You know this clearing is at the end of a Mystery Dungeon...[pause=60] right?")
  UI:WaitShowDialogue("And that Mystery Dungeons are full of feral Pokémon?")
  GAME:WaitFrames(30)
  GROUND:CharSetEmote(riolu, "question", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Confused_2')
  GAME:WaitFrames(60)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Mystery...[pause=60] Dungeon?")
  GAME:WaitFrames(60)
  UI:WaitShowDialogue("What...[pause=40] What's that?")

  GAME:WaitFrames(10)
  GROUND:CharSetEmote(player, "shock", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Shock')
  GAME:WaitFrames(50)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("You don't know what a Mystery Dungeon is?")

  GROUND:CharSetEmote(riolu, "sweatdrop", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweatdrop')

  GAME:WaitFrames(60)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("N-[pause=20]No?")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Should I?")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  Hop(player, 'None', 10)
  Hop(player, 'None', 10)
  UI:WaitShowDialogue("Of course you should!")
  UI:WaitShowDialogue("They are like, [pause=20]the most discussed about feature in the entire world!")

  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("They are?")
  UI:WaitShowDialogue("Well, I'm sure I haven't heard anything about them back home.")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("You haven't?")
  UI:WaitShowDialogue("That's impossible!")
  UI:WaitShowDialogue("Where even are you from?")
  GAME:WaitFrames(40)
  GROUND:EntTurn(riolu, Direction.DownLeft)
  GAME:WaitFrames(60)
  GROUND:EntTurn(riolu, Direction.Down)
  GAME:WaitFrames(3)
  GROUND:EntTurn(riolu, Direction.DownRight)
  GAME:WaitFrames(60)
  GROUND:EntTurn(riolu, Direction.Down)
  GAME:WaitFrames(50)
  GROUND:CharSetEmote(riolu, "sweating", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweating')
  
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("I can't remember...")


  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("You can't remember?")
  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Sad")
  UI:WaitShowDialogue("No...")
  GAME:WaitFrames(50)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Really?")
  UI:WaitShowDialogue("Nothing at all?")
  GAME:WaitFrames(80)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("No.[pause=40] Nothing...")

  GAME:WaitFrames(100)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Sorry to hear that, [color=#00ff00]Riolu[color].")
  GAME:WaitFrames(40)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("I mean!")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("I can't do anything, but there's a clinic over at [color=#fcacac]Twilight Town[color].")
  UI:WaitShowDialogue("I'm sure they'll have something to help you.")
  GAME:WaitFrames(30)
  GROUND:CharSetEmote(riolu, "question", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Confused_2')
  GAME:WaitFrames(80)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Hey, wait a second!")
  GAME:WaitFrames(40)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("What did you just call me?")
  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("What?")
  UI:WaitShowDialogue("What do you mean?")

  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue('You called me "[color=#00ff00]Riolu[color]".')

  GAME:WaitFrames(80)
  GROUND:CharSetEmote(player, "question", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Confused_2')

  GAME:WaitFrames(30)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Uhhh...")
  UI:WaitShowDialogue("Yeah, I did.")
  UI:WaitShowDialogue("Because,[pause=50] you know...")
  UI:WaitShowDialogue("You're a [color=#00ff00]Riolu[color]?")
  GAME:WaitFrames(80)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("...")
  GAME:WaitFrames(50)
  GROUND:EntTurn(riolu, Direction.DownLeft)
  GAME:WaitFrames(60)
  GROUND:EntTurn(riolu, Direction.Down)
  GAME:WaitFrames(5)
  GROUND:EntTurn(riolu, Direction.DownRight)
  GAME:WaitFrames(60)
  GROUND:EntTurn(riolu, Direction.Down)
  GAME:WaitFrames(60)
  GROUND:CharSetEmote(riolu, "shock", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Shock')
  GAME:WaitFrames(50)
  SOUND:PlayBGM("In the Depths of the Pit.ogg", true) 
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("What the-?!")
  UI:WaitShowDialogue("It's true!")
  UI:WaitShowDialogue("I'm a [color=#00ff00]Riolu[color]!")
  GAME:WaitFrames(15)
  GROUND:CharSetEmote(player, "sweatdrop", 1)
  SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Uhhh...")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("What happened to me?!")
  UI:WaitShowDialogue("I was a human last time I went to bed!")
  GAME:WaitFrames(30)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("[color=#00ff00]Ri[color]-")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("How could something like this happen?!")
  UI:WaitShowDialogue("People don't just...[pause=50] turn into a Pokémon overnight!")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("[color=#00ff00]Riolu[color]...")
  GAME:WaitFrames(20)

  GROUND:CharSetDrawEffect(riolu, DrawEffect.Trembling)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("God, what about my family?")
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("I can't remember them, but I'm sure I had one!")
  UI:SetSpeakerEmotion("Crying")
  UI:WaitShowDialogue("How am I going to explain them this?")
  UI:WaitShowDialogue("Am I even going to see them again?")

  SOUND:PlaySE("Battle/EVT_Emote_Complain_2")
  Hop(player, 'None', 10)
  Hop(player, 'None', 10)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Shouting")

  UI:WaitShowDialogue("[color=#00ff00]RIOLU[color]!")

  GAME:WaitFrames(40)  
  GROUND:CharEndDrawEffect(riolu, DrawEffect.Trembling)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Teary-Eyed")
  UI:WaitShowDialogue("H[pause=20]-Huh?")

  GAME:WaitFrames(60)
  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Sigh")
  UI:WaitShowDialogue("(He finally calmed down...)")
  GAME:WaitFrames(60)
  UI:SetSpeaker(player)

  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Hey,[pause=40] listen.")
  UI:WaitShowDialogue("You definitely don't look too good in the head, so my guess is that you hit it too hard somewhere.")
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("How about I show you the way to the town?")
  GAME:WaitFrames(60)


  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Teary-Eyed")
  UI:WaitShowDialogue("You...[pause=50] You would do that?")
  
  GAME:WaitFrames(60)
  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Sigh")
  UI:WaitShowDialogue("(And it's more than I should do...)")

  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Right)
  GAME:WaitFrames(60)

  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("(If the boss finds out about this...)")

  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(25)
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(20)
  UI:WaitShowDialogue("(I don't even want to think about what she'd do...)")

  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Up)
  GAME:WaitFrames(60)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Of course!")

  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("But I'm afraid I won't be able to acompany you all the way there.")
  GAME:WaitFrames(30)


  GROUND:CharSetEmote(riolu, "question", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Confused_2')
  GAME:WaitFrames(60)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Why not?")

  GAME:WaitFrames(30)
  GROUND:CharSetEmote(player, "sweatdrop", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweatdrop')
  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Ummm...")

  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Let's say I have some...[pause=50] personal problems with some Pokémon there.")
  GAME:WaitFrames(20)

  GROUND:CharSetEmote(riolu, "question", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Confused_2')
  GAME:WaitFrames(60)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Problems?")
  GAME:WaitFrames(40)

 
  UI:WaitShowDialogue("What kind of problems?")
  GAME:WaitFrames(20)
  GROUND:CharSetEmote(player, "sweating", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweating')
  GAME:WaitFrames(60)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Errm...")
  GAME:WaitFrames(20)

  GROUND:CharSetEmote(player, "exclaim", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("With all of this, I forgot to ask about your name!")

  GAME:WaitFrames(20)
  GROUND:CharSetEmote(riolu, "sweatdrop", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweatdrop')
  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Why are you avoiding the question?")

  GAME:WaitFrames(20)
  UI:SetSpeaker(player)
  GROUND:CharSetEmote(player, "sweating", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweating')
  GAME:WaitFrames(60)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Umm...")
  GAME:WaitFrames(50)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Errm...")
  GAME:WaitFrames(70)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("You must be imagining things!")
  UI:WaitShowDialogue("I'm not avoiding anything!")
  UI:WaitShowDialogue("Now how about you tell me your name so we can set off?")

  GAME:WaitFrames(20)
  GROUND:CharSetEmote(riolu, "sweatdrop", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweatdrop')
  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("You're weird...")
  GAME:WaitFrames(60)

  UI:SetSpeaker('', true, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Sigh")
  UI:WaitShowDialogue("(Don't make me talk, 'human'...)")
  GAME:WaitFrames(10)
  SOUND:FadeOutBGM(80)
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  local coro1 = TASK:BranchCoroutine(function() concealing_clearing.Emote(player, "exclaim") end)
  local coro2 = TASK:BranchCoroutine(function() concealing_clearing.Emote(riolu, "exclaim") end)
  local coro3 = TASK:BranchCoroutine(function() concealing_clearing.turnBack(player) end)
  TASK:JoinCoroutines({coro1,coro2,coro3})

 
 GROUND:Unhide('Boss')
  GROUND:Unhide('Jacques')
 
  UI:WaitShowDialogue("Where are we?")
  GAME:WaitFrames(30)
  UI:WaitShowDialogue("You're asking me?")
  UI:WaitShowDialogue("Maybe if you weren't so greedy, we wouldn't even be in this situation!")
  GAME:WaitFrames(50)
  UI:WaitShowDialogue("How do you expect me to run a guild that's bades on shops if I'm not?")
  UI:WaitShowDialogue("Where am I going to get the merchandise to sell from?")
  UI:WaitShowDialogue("Kecleon Wares?")


  GAME:WaitFrames(60)
  UI:WaitShowDialogue("Whatever. I think I see the end of the Dungeon.")

  GROUND:CharSetEmote(player, "shock", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Shock')
  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Oh no!")
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("[speed=0.7]Nononononononononononononononononononononononono!")

  GAME:WaitFrames(30)
  GROUND:CharSetEmote(riolu, "question", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Confused_2')
  GAME:WaitFrames(60)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("What's the problem?")
  GAME:WaitFrames(20)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("...")
  GAME:WaitFrames(80)
  UI:WaitShowDialogue("I'm sorry.")

  GAME:WaitFrames(20)
  GROUND:CharSetEmote(riolu, "sweating", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweating')
  GAME:WaitFrames(60)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Sorry for what?")
  GAME:WaitFrames(40)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("[color=#03f8fc]Jacques[color], did you hear that?")
  GAME:WaitFrames(40)
  UI:WaitShowDialogue("Sure did, [color=#03f8fc]Ma'am[color]!")
  UI:WaitShowDialogue("Let's go! Come on, move it, move it!")

  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Should we be concerned?")
  
  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("...")
  GAME:WaitFrames(60)


  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Hey, [color=#00ffff]Ma'am[color]. Is that...")
  GAME:WaitFrames(80)
  UI:WaitShowDialogue("Yes, she is!")

  SOUND:PlayBGM("In the Depths of the Pit.ogg", true) 
  
  local coro1 = TASK:BranchCoroutine(function() concealing_clearing.moveUp(thievul, 100, false, 2) end)
  local coro2 = TASK:BranchCoroutine(function() concealing_clearing.moveUp(boss, 100, false, 2) end)
  TASK:JoinCoroutines({coro1,coro2})
  GAME:WaitFrames(50)
  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("You actually made it to the end!")

  UI:SetSpeaker(thievul)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("What a relief!")
  UI:WaitShowDialogue("[color=#00ffff]Ma'am[color] here was actually worried about you!")

  GAME:WaitFrames(80)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("She...[pause=70] was?")
  GAME:WaitFrames(100)

  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Look...")
  GAME:WaitFrames(90)
  UI:WaitShowDialogue("I'm not usually one to apologize, but I think you deserve one this time, [color=#fff30a]Sprigatito[color]...")
  UI:WaitShowDialogue("Sending you on your own to the inside of a dungeon while we were being chased was a very rash thing to do, especially knowing you joined no more than two weeks ago.")
  UI:WaitShowDialogue("So...")
  GAME:WaitFrames(50)
  UI:WaitShowDialogue("Sorry...")
  GAME:WaitFrames(90)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Did you just-?")
  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("Don't push it.")
  GAME:WaitFrames(60)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Geez, okay.")
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Thanks, [color=#03f8fc]Ma'am[color].")

  GROUND:EntTurn(thievul, Direction.UpLeft)
  GAME:WaitFrames(5)
  GROUND:EntTurn(thievul, Direction.Left)
  GAME:WaitFrames(40)

  UI:SetSpeaker(thievul)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("See?")
  UI:WaitShowDialogue("It wasn't that difficult, was it?")
  GAME:WaitFrames(20)
  GROUND:EntTurn(boss, Direction.UpRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(boss, Direction.Right)
  GAME:WaitFrames(50)
  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("You don't push it either.")
  UI:WaitShowDialogue("Do I remind the sole reason why you're here?")

  GAME:WaitFrames(30)
  UI:SetSpeaker(thievul)
  UI:SetSpeakerEmotion("Joyous")
  GROUND:CharSetEmote(thievul, "happy", 0)
  UI:WaitShowDialogue("No need, [color=#03f8fc]Ma'am[color]")
  GROUND:CharSetEmote(thievul, "happy", 1)

  GAME:WaitFrames(60)

  GROUND:CharSetEmote(riolu, "sweating", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweating')

  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Special3")
  UI:WaitShowDialogue("I think I'm missing something here...")
  GAME:WaitFrames(10)


  SOUND:PlaySE('Battle/EVT_Emote_Exclaim')
  local coro1 = TASK:BranchCoroutine(function() concealing_clearing.Emote(thievul, "notice") end)
  local coro2 = TASK:BranchCoroutine(function() concealing_clearing.Emote(boss, "notice") end)
  local coro3 = TASK:BranchCoroutine(function() concealing_clearing.turnUp(thievul, "th") end)
  local coro4 = TASK:BranchCoroutine(function() concealing_clearing.turnUp(boss, "bo") end)
  TASK:JoinCoroutines({coro1,coro2,coro3,coro4})
  GAME:WaitFrames(90)


  UI:SetSpeaker(thievul)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Wait, who's that guy over there?")
  GAME:WaitFrames(60)
  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Are you talking about the [color=#00ff00]Riolu[color] that's standing there, listening to eveything?")
  GAME:WaitFrames(60)
  SOUND:FadeOutBGM(80)
  UI:ResetSpeaker()
  UI:WaitShowDialogue(".[pause=60].[pause=60].[pause=60]")
  GAME:WaitFrames(90)
  SOUND:PlaySE('Battle/EVT_Emote_Shock')
  local coro1 = TASK:BranchCoroutine(function() concealing_clearing.Emote(thievul, "shock") end)
  local coro2 = TASK:BranchCoroutine(function() concealing_clearing.Emote(boss, "shock") end)

  TASK:JoinCoroutines({coro1,coro2})
  
  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("What are you doing here?!")
  GAME:WaitFrames(80)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue("Oh, great!")
  UI:WaitShowDialogue("As if this day couldn't get any worse...")

  GROUND:CharSetEmote(boss, "angry", 2)
  SOUND:PlaySE("Battle/EVT_Emote_Complain_2")
  Hop(boss, 'None', 10)
  Hop(boss, 'None', 10)

  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("Who are you?")

  UI:WaitShowDialogue("[color=#fff30a]Sprigatito[color], stand back! We don't know if he's an explorer!")
  
  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Explorer? What's that?")

  GAME:WaitFrames(40)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("No, wait!")
  UI:WaitShowDialogue("He doesn't remember anything!")
  UI:WaitShowDialogue("He's got amnesia!")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("He can't be an exlorer if he's got amnesia,[pause=50] right?")
  GAME:WaitFrames(60)
  UI:SetSpeaker(thievul)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Amnesia?")

  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("That's one of the oldest tricks in the book.")
  UI:WaitShowDialogue("He could very well be one of the cops that was after us, pretending not to know anything!")
  UI:WaitShowDialogue('"Lying 101", if it were in a book.')
  GAME:WaitFrames(40)
  GROUND:EntTurn(player, Direction.DownRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Right)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Up)
  GAME:WaitFrames(80)
  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Right)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.DownRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Down)
  GAME:WaitFrames(80)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("You really think so?")

  GAME:WaitFrames(50)
  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Joyous")
  UI:WaitShowDialogue("Sweetie, I've been in this business ever since before you were even hatched.")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("I suppose, but...")

  GAME:WaitFrames(60)

  UI:SetSpeaker(thievul)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("What do we do with the [color=#00ff00]Riolu[color], [color=#03f8fc]Ma'am[color]?")

  GAME:WaitFrames(50)
  GROUND:CharSetEmote(riolu, "sweating", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Sweating')
  GAME:WaitFrames(40)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("What?")

  GAME:WaitFrames(80)




  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("That's easy!")
  UI:WaitShowDialogue("Stand aside for a moment.")
  GAME:WaitFrames(40)
  local coro1 = TASK:BranchCoroutine(function() concealing_clearing.moveRight(boss, 8, false, 2, false) end)
  local coro2 = TASK:BranchCoroutine(function() concealing_clearing.moveRight(thievul, 8, false, 2, true) end)
  TASK:JoinCoroutines({coro1,coro2})
  --GROUND:MoveInDirection(boss, Direction.Right, 8, false, 2)

  GAME:WaitFrames(50)

  UI:SetSpeakerEmotion("Special2")
  UI:WaitShowDialogue("Let's show him what happens to those who mess with us.")

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("Should I...?")

  UI:SetSpeaker(thievul)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Yeah, you should get out of the way.")
  GAME:WaitFrames(10)
  GROUND:MoveInDirection(player, Direction.Left, 15, false, 2)
  GROUND:EntTurn(player, Direction.UpLeft)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Up)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(player, Direction.Right)
  GAME:WaitFrames(40)

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Woah, what?")
  UI:WaitShowDialogue("What's going on?")

  GAME:WaitFrames(60)

  UI:SetSpeaker(boss)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue("You don't need to know, [color=#00ff00]Riolu[color].")
  UI:SetSpeakerEmotion("Special2")
  UI:WaitShowDialogue("Goodnight!")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, riolu.CurrentForm.Species, riolu.CurrentForm.Form, riolu.CurrentForm.Skin, riolu.CurrentForm.Gender)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("What's that supposed to me-?!")
  GROUND:MoveInDirection(boss, Direction.Up, 17, true, 4)
  GAME:FadeOut(false, 1)
  SOUND:PlaySE("Battle/DUN_Tackle")

  GAME:WaitFrames(300)
  SV.conceal_forest_entrance.found_player = true
  GAME:EnterZone('thieves_hideout', -1, 1, 0)
  

end
function concealing_clearing.Emote(character, emote)
  GROUND:CharSetEmote(character, emote, 1)


end
function concealing_clearing.moveRight(char, time, running, speed, who)
  GROUND:MoveInDirection(char, Direction.Right, time, running, speed)

  GAME:WaitFrames(10)
  GROUND:EntTurn(char, Direction.UpRight)
  GAME:WaitFrames(5)
  GROUND:EntTurn(char, Direction.Up)
  if who == true then
    GAME:WaitFrames(5)
    GROUND:EntTurn(char, Direction.UpLeft)



  end
end
function concealing_clearing.turnUp(character, who)
 if who == 'bo' then
  GROUND:EntTurn(character, Direction.UpRight)
  GAME:WaitFrames(3)
  GROUND:EntTurn(character, Direction.Up)

  elseif who == 'th' then
    GROUND:EntTurn(character, Direction.UpLeft)
    GAME:WaitFrames(3)
    GROUND:EntTurn(character, Direction.Up)
  end

  
end
function concealing_clearing.turnBack(character)
  GROUND:EntTurn(character, Direction.UpRight)
  GAME:WaitFrames(3)
  GROUND:EntTurn(character, Direction.Right)
  GAME:WaitFrames(3)
  GROUND:EntTurn(character, Direction.DownRight)
  GAME:WaitFrames(3)
  GROUND:EntTurn(character, Direction.Down)
  
end
function Hop(chara, anim, height, duration, pause, sound)
  anim = anim or 'None'
  height = height or 10
  duration = duration or 10
  if pause == nil then pause = true end
  if sound == nil then sound = false end

  local animId = RogueEssence.Content.GraphicsManager.GetAnimIndex(anim)
  GROUND:CharSetAction(chara, RogueEssence.Ground.HopGroundAction(chara.Position, chara.Direction, animId, height, duration))
  
  if sound then
      SOUND:PlayBattleSE("EVT_Emote_Startled")
  end
  
  if pause then 
      GAME:WaitFrames(duration)
  end

end


function concealing_clearing.moveCamera(x, y, time)
  GAME:MoveCamera(x, y, time, false)


end
function concealing_clearing.moveUp(char, time, running, speed)
  GROUND:MoveInDirection(char, Direction.Up, time, running, speed)


end

---concealing_clearing.Exit(map)
--Engine callback function
function concealing_clearing.Exit(map)


end

---concealing_clearing.Update(map)
--Engine callback function
function concealing_clearing.Update(map)


end

---concealing_clearing.GameSave(map)
--Engine callback function
function concealing_clearing.GameSave(map)


end

---concealing_clearing.GameLoad(map)
--Engine callback function
function concealing_clearing.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return concealing_clearing

