--[[
    init.lua
    Created: 05/02/2024 10:08:10
    Description: Autogenerated script file for the map room_lily_and_celia.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local room_lily_and_celia = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---room_lily_and_celia.Init(map)
--Engine callback function
function room_lily_and_celia.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies()
  local partners = CH('Teammate1')
  AI:SetCharacterAI(partners, "ai.ground_partner", CH('PLAYER'), partners.Position)
  AI:EnableCharacterAI(partners)
  partners.CollisionDisabled = true
end

---room_lily_and_celia.Enter(map)
--Engine callback function
function room_lily_and_celia.Enter(map)

  GAME:FadeIn(20)

end

---room_lily_and_celia.Exit(map)
--Engine callback function
function room_lily_and_celia.Exit(map)


end

---room_lily_and_celia.Update(map)
--Engine callback function
function room_lily_and_celia.Update(map)


end

---room_lily_and_celia.GameSave(map)
--Engine callback function
function room_lily_and_celia.GameSave(map)
  local partner = CH('Teammate1')
  SV.partner.positionX = partner.Position.X
	SV.partner.positionY = partner.Position.Y
	SV.partner.direction = DirToNum(partner.Direction)

end

---room_lily_and_celia.GameLoad(map)
--Engine callback function
function room_lily_and_celia.GameLoad(map)

  local partners = CH('Teammate1')
  GROUND:TeleportTo(partners, SV.partner.positionX, SV.partner.positionY, NumToDir(SV.partner.direction))
  

	AI:SetCharacterAI(partners, "ai.ground_partner", CH('PLAYER'), partners.Position)
  AI:EnableCharacterAI(partners)
  partners.CollisionDisabled = true
  
  GAME:FadeIn(20)

end
function DirToNum(dir)
	--up is 0, upright is 1, ... up left is 7
	local num = -1
	if dir == Direction.Up then
		num = 0
	elseif dir == Direction.UpRight then
		num = 1
	elseif dir == Direction.Right then
		num = 2
	elseif dir == Direction.DownRight then
		num = 3
	elseif dir == Direction.Down then
		num = 4
	elseif dir == Direction.DownLeft then
		num = 5
	elseif dir == Direction.Left then
		num = 6
	elseif dir == Direction.UpLeft then
		num = 7
	end
	
	return num
	
end
--converts a number to a direction
function NumToDir(num)
	local dir = Direction.None
	if num % 8 == 0 then 
		dir = Direction.Up
	elseif num % 8 == 1 then
		dir = Direction.UpRight
	elseif num % 8 == 2 then
		dir = Direction.Right
	elseif num % 8 == 3 then
		dir = Direction.DownRight
	elseif num % 8 == 4 then
		dir = Direction.Down
	elseif num % 8 == 5 then
		dir = Direction.DownLeft
	elseif num % 8 == 6 then
		dir = Direction.Left
	elseif num % 8 == 7 then
		dir = Direction.UpLeft
	end

	return dir
end 
-------------------------------
-- Entities Callbacks
-------------------------------
function room_lily_and_celia.paper_Action(obj, activator)
  GAME:CutsceneMode(true)

  UI:ResetSpeaker()
  UI:WaitShowDialogue('A piece of paper.[pause=50] It reads:[br]"We still miss you..."')
  UI:WaitShowDialogue("There's more writen on it, but you decide to leave it be.")
  GAME:CutsceneMode(false)

  
end
function room_lily_and_celia.alcohol_Action(obj, activator)
  GAME:CutsceneMode(true)

  UI:ResetSpeaker()
  UI:WaitShowDialogue("A drink that smells strongly like liquor.")

  GAME:CutsceneMode(false)
  
end
function room_lily_and_celia.exit_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  SV.partner.entrance = 2
  GAME:EnterZone('thieves_hideout', -1, 11, 3)
  



end

return room_lily_and_celia

