--[[
    init.lua
    Created: 02/03/2024 13:19:51
    Description: Autogenerated script file for the map shady_clearing.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local shady_clearing = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---shady_clearing.Init(map)
--Engine callback function
function shady_clearing.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies()
end

---shady_clearing.Enter(map)
--Engine callback function
function shady_clearing.Enter(map)
  GROUND:Hide('Plusle')
  GROUND:Hide('Minun')
 
  GAME:CutsceneMode(true)
  GAME:WaitFrames(90)
  SOUND:PlayBGM("In the Depths of the Pit.ogg", true) 
  GAME:MoveCamera(190, 140, 1, false)


  if SV.guild_maze_clearing.test_done == false then
  
    if SV.guild_maze_clearing.first_boss_intro == false and SV.guild_maze_clearing.beat_boss == false then
      overchargeCutscene()

    elseif SV.guild_maze_clearing.first_boss_intro == true and SV.guild_maze_clearing.beat_boss == false then
      faintedOverchargeCutscene()

    
    elseif SV.guild_maze_clearing.beat_boss == true then
      YouWin()
    end

  elseif SV.guild_maze_clearing.test_done == true then
    GROUND:Hide('Gummi')
    UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 50)
    GAME:WaitFrames(50)
    UI:WaitHideTitle(50)
      --regular go back cutscene


  end



end
function overchargeCutscene()
  local player = CH('PLAYER')
  local partner = CH('Teammate1')
  local plusle = CH('Plusle')
  local minun = CH('Minun')


  GAME:FadeIn(20)
  local coro1 = TASK:BranchCoroutine(function() moveTo(player, 161, 135, 1.5) end)
  local coro2 = TASK:BranchCoroutine(function() moveTo(partner, 204, 135, 1.5) end)
  TASK:JoinCoroutines({coro1,coro2})
  GAME:WaitFrames(60)
  GROUND:CharSetEmote(player, "question", 1)
  SOUND:PlaySE('Battle/EVT_Emote_Confused_2')
  GAME:WaitFrames(100)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("What's that?")
  UI:WaitShowDialogue("Is that a gummy made out of gold?")
  GAME:WaitFrames(70)
  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("That's a Gold Gummi.")
  UI:WaitShowDialogue("A small snack that psychic type Pokémon like a lot, mostly because of the boost to their abilities they give.")

  UI:WaitShowDialogue("But I don't understand how it has gotten here, or even why.")
  GAME:WaitFrames(60)

  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(4)
  GROUND:EntTurn(player, Direction.Right)
  GAME:WaitFrames(60)
  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("Do you think that could be the item we're looking for?")
  UI:WaitShowDialogue("I mean...")
  UI:WaitShowDialogue("It's a bit suspicious, don't you think?")
  GROUND:EntTurn(partner, Direction.UpLeft)
  GAME:WaitFrames(4)
  GROUND:EntTurn(partner, Direction.Left)
  GAME:WaitFrames(60)
  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("It's true that I've never seen a Gold Gummi in this dungeon, but...")
  UI:WaitShowDialogue("There could just be a really rare object...")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  
  UI:WaitShowDialogue("It's not!")
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
 
  local coro1 = TASK:BranchCoroutine(function() THEEmoteFunction(player, "exclaim") end)
  local coro2 = TASK:BranchCoroutine(function() THEEmoteFunction(partner, "exclaim") end)
  TASK:JoinCoroutines({coro1,coro2})
  GROUND:EntTurn(player, Direction.Up)
  GROUND:EntTurn(partner, Direction.Up)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Who said that?")
  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue("Who's there?")

  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Just...[pause=50]")
  UI:WaitShowDialogue("Wait a moment!")

  GAME:WaitFrames(40)

  UI:WaitShowDialogue("Tell me why did we have to get onto that tree again?")

  UI:WaitShowDialogue("Where else did you expect us to hide?")

    SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
    local coro1 = TASK:BranchCoroutine(function() THEEmoteFunction(player, "sweatdrop") end)
    local coro2 = TASK:BranchCoroutine(function() THEEmoteFunction(partner, "sweatdrop") end)
    TASK:JoinCoroutines({coro1,coro2})
  GAME:WaitFrames(110)

  UI:SetSpeaker(player)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("What's going on?")
  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Stunned")
  UI:WaitShowDialogue("I wish I could tell you...")
  GAME:WaitFrames(60)
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue("Alright, are you set, bro?")
  UI:WaitShowDialogue("As set as I'll ever be!")
  UI:WaitShowDialogue("Okay, let's do this!")
  SOUND:FadeOutBGM(80)
  SOUND:PlayBattleSE('EVT_Battle_Transition')
  GAME:FadeOut(true, 80)
  GAME:WaitFrames(70)
  GROUND:Unhide('Plusle')
  GROUND:Unhide('Minun')
  GAME:FadeIn(30)

  SOUND:PlaySE('Battle/EVT_Emote_Shock')
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
  local coro1 = TASK:BranchCoroutine(function() THEEmoteFunction(player, "exclaim") end)
  local coro2 = TASK:BranchCoroutine(function() THEEmoteFunction(partner, "shock") end)
  TASK:JoinCoroutines({coro1,coro2})
  GAME:WaitFrames(90)

  UI:SetSpeaker(partner)
  UI:SetSpeakerEmotion("Surprised")
  UI:WaitShowDialogue(plusle:GetDisplayName().."?![pause=0] " .. minun:GetDisplayName() .. "?!")
  UI:WaitShowDialogue("What are you doing here?")

  UI:SetSpeaker(plusle)
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue("Did you really think that the test would be that easy?")
  GAME:WaitFrames(60)

  UI:SetSpeaker(minun)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue("Hello again, " .. partner:GetDisplayName() .. "!")

  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(4)
  GROUND:EntTurn(player, Direction.Right)
  GAME:WaitFrames(50)

  Dialogue(player, "Worried", "Do you know these guys?")
 
  GAME:WaitFrames(40)
  GROUND:EntTurn(partner, Direction.UpLeft)
  GAME:WaitFrames(4)
  GROUND:EntTurn(partner, Direction.Left)
  GAME:WaitFrames(40)
  Dialogue(partner, "Happy", "Yeah!")
  UI:WaitShowDialogue("They are one of the teams in the guild!")
  GAME:WaitFrames(30)
  GROUND:EntTurn(partner, Direction.UpLeft)
  GAME:WaitFrames(4)
  GROUND:EntTurn(partner, Direction.Up)
  Dialogue(partner, "Worried", "Though, I don't know what they're doing here...")
  GAME:WaitFrames(30)
  GROUND:EntTurn(player, Direction.UpRight)
  GAME:WaitFrames(4)
  GROUND:EntTurn(player, Direction.Up)
  GAME:WaitFrames(50)

  Dialogue(player, "Worried", "May I ask who you are?")
  GAME:WaitFrames(40)
  Dialogue(plusle, "Determined", "We are team [color=#FFA5FF]Overcharge[color]!")
  Dialogue(minun, "Determined", "And we are the last obstacle before you can complete your test!")

  GAME:WaitFrames(60)
  Dialogue(player, "Stunned", "Last obstacle?")

  Dialogue(minun, "Happy", "Yeah!")
  GAME:WaitFrames(60)

  Dialogue(player, "Worried", "And what's that obstacle?")
  
  Dialogue(plusle, "Happy", "That's easy!")
  Dialogue(plusle, "Happy", "Your last task before getting to the Gummi is...")


  SOUND:PlayBattleSE("EVT_Battle_Flash")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(6)
  GAME:FadeIn(1)
  Dialogue(plusle, "Determined", "Beating us in a battle!")

  SOUND:PlayBGM("A13. Threat.ogg", true) 
  Dialogue(player, "Surprised", "A battle?![br]What do you mean a battle?!")
   
  Dialogue(plusle, "Determined", "What,[pause=40] too scared to fight?")
  
  Dialogue(player, "Surprised", "Yes![br]I don't know how to!")

  Dialogue(plusle, "Determined", "Well, you better learn now, because you aren't taking the Gummi without passing through us!")

  GROUND:EntTurn(partner, Direction.Left)
  Dialogue(partner, "Determined", player:GetDisplayName().."![br]Are you ready?")

  GROUND:EntTurn(player, Direction.Right)
  Dialogue(player, "Surprised", "Of course I'm not![br]I don't know how to throw a punch!")

  GROUND:EntTurn(partner, Direction.Up)
  Dialogue(partner, "Determined", "Well, you better learn how!")
  Dialogue(partner, "Determined", "Don't worry, I got your back!")
  
  Dialogue(player, "Stunned", "...")
  GAME:WaitFrames(50)
  GROUND:EntTurn(player, Direction.Up)

  Dialogue(player, "Determined", "Okay!")
  
  Dialogue(minun, "Determined", "We're gonna give you a feeling of what the [color=#00ffff]Thieves Guild[color] is really about![br]You're gonna have such a tough time tomorrow when you wake up with all the bruises you're gonna have!")
  GAME:WaitFrames(30)
 
  GROUND:CharSetEmote(minun, "sweating", 1)
      SOUND:PlaySE('Battle/EVT_Emote_Sweating')
  GAME:WaitFrames(90)
  GROUND:EntTurn(minun, Direction.Left)

  Dialogue(minun, "Worried", "Was that good enough?[br]Maybe I went too far...")
  GAME:WaitFrames(60)
  GROUND:EntTurn(plusle, Direction.Right)

  Dialogue(plusle, "Sigh", "We really should practice your trash talking before a battle.")
  GAME:WaitFrames(40)

  GROUND:EntTurn(plusle, Direction.Down)
  Dialogue(plusle, "Determined", "But for now...")
  GROUND:EntTurn(minun, Direction.Down)

  SOUND:PlayBattleSE("EVT_Battle_Flash")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(6)
  GAME:FadeIn(1)
  Dialogue(plusle, "Determined", "Let's make this challenge as tough as possible!")

  Dialogue(partner, "Determined", "Watch out, "..player:GetDisplayName().."![br]Here they come!")

  SOUND:FadeOutBGM(50)

  COMMON.BossTransition()

  GAME:CutsceneMode(false)
  SV.guild_maze_clearing.first_boss_intro = true
  GAME:EnterZone("thieves_hideout", 1, 0, 0)

end
function faintedOverchargeCutscene()
  local player = CH('PLAYER')
  local partner = CH('Teammate1')
  local plusle = CH('Plusle')
  local minun = CH('Minun')

  GROUND:Unhide('Plusle')
  GROUND:Unhide('Minun')

  GROUND:EntTurn(minun, Direction.Left)
  GROUND:EntTurn(plusle, Direction.Right)
  GAME:WaitFrames(100)
  GAME:FadeIn(30)

  GAME:WaitFrames(50)

  GROUND:CharSetDrawEffect(minun, DrawEffect.Trembling)
  GAME:WaitFrames(30)
  GROUND:CharEndDrawEffect(minun, DrawEffect.Trembling)
  GAME:WaitFrames(50)
  Dialogue(minun, "Pain", "Are you sure we shouldn't have held back even a little?")
  Dialogue(minun, "Pain", player:GetDisplayName() .. " really looked like he was serious about not knowing how to fight...")
  GAME:WaitFrames(20)
  
  GROUND:CharSetEmote(minun, "sweating", 1)
      SOUND:PlaySE('Battle/EVT_Emote_Sweating')
  GAME:WaitFrames(50)
  Dialogue(minun, "Surprised", "What if we injured them too badly?")
  GAME:WaitFrames(50)
  Dialogue(plusle, "Worried", "Hey, bro![br]Don't worry about it!")

  Dialogue(plusle, "Determined", "Of course we couldn't hold back!")
  Dialogue(plusle, "Determined", "We are supposed to be the last challenge!")
  Dialogue(plusle, "Determined", "We have to give our all against them!")
  Dialogue(minun, "Worried", "I know, [pause=10]but...")

  SOUND:FadeOutBGM(60)
  
  GROUND:EntTurn(minun, Direction.Down)
  GROUND:EntTurn(plusle, Direction.Down)
  SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
  local coro1 = TASK:BranchCoroutine(function() THEEmoteFunction(plusle, "exclaim") end)
  local coro2 = TASK:BranchCoroutine(function() THEEmoteFunction(minun, "exclaim") end)
  TASK:JoinCoroutines({coro1,coro2})
  UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)

  UI:WaitShowDialogue("Hey!")


  local coro1 = TASK:BranchCoroutine(function() moveTo(player, 161, 135, 2) end)
  local coro2 = TASK:BranchCoroutine(function() moveTo(partner, 204, 135, 2) end)
  TASK:JoinCoroutines({coro1,coro2})

  GAME:WaitFrames(60)


  SOUND:PlayBGM("A13. Threat.ogg", true) 
  Dialogue(player, "Determined", "We are back to try again!")
  Dialogue(partner, "Determined", "And you won't get us this time!")
  GAME:WaitFrames(50)

  Dialogue(minun, "Surprised", "We have to fight them again?!")
  Dialogue(plusle, "Determined", "Looks like it!")
  Dialogue(plusle, "Determined", "But it doesn't matter how many times we have to do it!")
  Dialogue(plusle, "Determined", "We'll win each time you try us!")
  GAME:WaitFrames(50)

  Dialogue(player, "Determined", "We'll see about that!")


  COMMON.BossTransition()

  GAME:CutsceneMode(false)
  
  GAME:EnterZone("thieves_hideout", 1, 0, 0)



end
function YouWin()
  GROUND:Unhide('Plusle')
  GROUND:Unhide('Minun')
  local player = CH('PLAYER')
  local partner = CH('Teammate1')
  local plusle = CH('Plusle')
  local minun = CH('Minun')

  GAME:CutsceneMode(true)

  SOUND:PlayBGM("In the Depths of the Pit.ogg", true) 
  GAME:MoveCamera(190, 140, 1, false)
  GROUND:TeleportTo(player, 161, 135, Direction.Up)
  GROUND:TeleportTo(partner, 204, 135, Direction.Up)
  GAME:FadeIn(30)
  
  Ouchie()

  Dialogue(minun, "Surprised", "Woah!")
  GAME:WaitFrames(40)

  Dialogue(plusle, "Surprised", "I thought you didn't know how to fight!")
 
  Dialogue(player, "Stunned", "...")
  GAME:WaitFrames(60) 
  Dialogue(player, "Determined", "Does that mean we won?")
  Dialogue(plusle, "Stunned", "Geez, yes!")
  Dialogue(plusle, "Stunned", "We can barely even stand up!")
  Dialogue(minun, "Pain", "Huff...[pause=50] Huff...[pause=50]")
  Dialogue(minun, "Pain", "For our first actual battle...[pause=50] it was fun...")
  GAME:WaitFrames(50)

  GROUND:EntTurn(plusle, Direction.UpRight)
  GAME:WaitFrames(40)
  SOUND:PlaySE('Item_Grab')
  GROUND:Hide('Gummi')
  GAME:WaitFrames(40)
  GROUND:EntTurn(plusle, Direction.Right)
  GAME:WaitFrames(4)
  GROUND:EntTurn(plusle, Direction.DownRight)
  GAME:WaitFrames(4)
  GROUND:EntTurn(plusle, Direction.Down)
  GAME:WaitFrames(60)
  Dialogue(plusle, "Happy", "I think you guys earned this!")
	GROUND:MoveInDirection(plusle, Direction.Down, 15, false, 2)
  GAME:WaitFrames(50)

  Monologue(plusle:GetDisplayName() .. " gave " .. player:GetDisplayName() .. " the Gummi.")
  GAME:WaitFrames(60)
  Dialogue(plusle, "Normal", "Show this to the boss so she knows you've beaten the test.")
  Dialogue(plusle, "Happy", "I guess this means we're guildmates now!")
  Dialogue(minun, "Happy", "Welcome to the guild, " .. player:GetDisplayName().. "!")

  GAME:WaitFrames(40)

  GROUND:EntTurn(partner, Direction.UpLeft)
  GAME:WaitFrames(4) 
  GROUND:EntTurn(partner, Direction.Left)

  GAME:WaitFrames(30)

  Dialogue(partner, "Happy", "You did it, " ..player:GetDisplayName() .. "!")
  GAME:WaitFrames(50)

  Dialogue(player, "Stunned", "That's it?[pause=0] We're done?")
  Dialogue(plusle, "Happy", "Yup!")
  GAME:WaitFrames(60)
  GROUND:EntTurn(minun, Direction.DownLeft)
  Dialogue(minun, "Worried", "Can we get out of here now?")
  Dialogue(minun, "Worried", "This place is getting on my nerves...")

  GROUND:EntTurn(partner, Direction.UpLeft)
  GAME:WaitFrames(4) 
  GROUND:EntTurn(partner, Direction.Up)
  Dialogue(partner, "Worried", "Yeah let's get out already.")
  GAME:WaitFrames(30) 

  local coro1 = TASK:BranchCoroutine(function() GROUND:EntTurn(partner, Direction.UpLeft)
                                                GAME:WaitFrames(4) 
                                                GROUND:EntTurn(partner, Direction.Left) end)

  local coro2 = TASK:BranchCoroutine(function() GROUND:EntTurn(player, Direction.UpRight)
                                                GAME:WaitFrames(4) 
                                                GROUND:EntTurn(player, Direction.Right)  end)
  TASK:JoinCoroutines({coro1,coro2})
  


  Dialogue(partner, "Happy", "Time to deliver the news to the Boss!")
  GROUND:CharSetAnim(player, "Nod", false)
  GAME:WaitFrames(60) 
  Dialogue(player, "Determined", "Let's go!")

  GAME:FadeOut(false, 20)
  GAME:WaitFrames(70) 
  SV.guild_maze_clearing.test_done = true
  GAME:EndDungeonRun(RogueEssence.Data.GameProgress.ResultType.Cleared, "thieves_hideout", -1, 5, 0, true, true)
  GAME:EnterZone("thieves_hideout", -1, 5, 0)
end
function Ouchie(char)
  SOUND:PlayBattleSE("EVT_Battle_Flash")
  GAME:FadeOut(true, 1)
 -- GROUND:CharSetAction(char, RogueEssence.Ground.PoseGroundAction(char.Position, char.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pain")))
  GAME:WaitFrames(6)
  GAME:FadeIn(1)



end
function Monologue(str)
	UI:ResetSpeaker(false)
	UI:SetCenter(true)
	UI:SetAutoFinish(true)
	UI:WaitShowDialogue(str)
	UI:SetAutoFinish(false)
	UI:SetCenter(false)
end 
function Dialogue(sp, emote, txt)
  UI:SetSpeaker(sp)
  UI:SetSpeakerEmotion(emote)
  UI:WaitShowDialogue(txt)


end



function moveTo(char, x, y, speed)

  GROUND:MoveToPosition(char, x, y, false, speed)

end
function back(char)
  GROUND:AnimateInDirection(char, "Walk", Direction.Up, Direction.Down, 24, 3, 2)

end
function THEEmoteFunction(char, emote)
  GROUND:CharSetEmote(char, emote, 1)

end





---shady_clearing.Exit(map)
--Engine callback function
function shady_clearing.Exit(map)


end

---shady_clearing.Update(map)
--Engine callback function
function shady_clearing.Update(map)


end

---shady_clearing.GameSave(map)
--Engine callback function
function shady_clearing.GameSave(map)


end

---shady_clearing.GameLoad(map)
--Engine callback function
function shady_clearing.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return shady_clearing

