--[[
    init.lua
    Created: 05/07/2024 09:29:12
    Description: Autogenerated script file for the map room_player_and_partner.
]]--
-- Commonly included lua functions and data
require 'common'
require 'ground.room_player_and_partner.room_player_and_partner_ch2'
-- Package name
local room_player_and_partner = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---room_player_and_partner.Init(map)
--Engine callback function
function room_player_and_partner.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')
  GROUND:Hide('Kit')

  partner.CollisionDisabled = true
  if not SV.sleeping then 
    GROUND:Hide('fire')
    AI:SetCharacterAI(partner, "ai.ground_partner", CH('PLAYER'), partner.Position)
    AI:EnableCharacterAI(partner)
  else
    GROUND:Unhide('fire') -- Having fire burn and steal your oxygen while you sleep inside a cave is totally not risky at all, what do you mean.
  end
end

---room_player_and_partner.Enter(map)
--Engine callback function
function room_player_and_partner.Enter(map)
  local partner = CH('Teammate1')
  local player = CH('PLAYER')

  if not SV.sleeping then
    SOUND:PlayBGM("Wigglytuff's Guild.ogg", true) 
  else
    GAME:MoveCamera(202, 130, 1, false)
    SOUND:PlayBGM("Goodnight.ogg", true) 
    local marker = MRKR('sleepy_part')
		GROUND:TeleportTo(partner, marker.Position.X, marker.Position.Y, marker.Direction)
    GROUND:CharTurnToChar(partner, player)
    GROUND:AddMapStatus("dark")
    GAME:CutsceneMode(true)
    if SV.progression.chapter == 1 then
      if not SV.guildmasters_office.officially_joined then
      
        firstCutscene()

      end
    elseif SV.progression.chapter == 2 then
      room_player_and_partner_ch2.firstDaySuccessfulCut()
     
      
    
    end
  end
  GAME:FadeIn(20)

end

---room_player_and_partner.Exit(map)
--Engine callback function
function room_player_and_partner.Exit(map)


end

---room_player_and_partner.Update(map)
--Engine callback function
function room_player_and_partner.Update(map)


end

---room_player_and_partner.GameSave(map)
--Engine callback function
function room_player_and_partner.GameSave(map)
  local partner = CH('Teammate1')
  SV.partner.positionX = partner.Position.X
  SV.partner.positionY = partner.Position.Y
  SV.partner.direction = DirToNum(partner.Direction)

end

---room_player_and_partner.GameLoad(map)
--Engine callback function
function room_player_and_partner.GameLoad(map)
  SOUND:PlayBGM("Wigglytuff's Guild.ogg", true) 

  local partners = CH('Teammate1')
  GROUND:TeleportTo(partners, SV.partner.positionX, SV.partner.positionY, NumToDir(SV.partner.direction))

	AI:SetCharacterAI(partners, "ai.ground_partner", CH('PLAYER'), partners.Position)
  AI:EnableCharacterAI(partners)
  partners.CollisionDisabled = true
  GAME:FadeIn(20)

end
function Dialogue(sp, state, emote, txt)
  if state == 0 then --Speaker is unknown and invisible
    UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  elseif state == 1 then --Speaker is unknown, but visible (AKA, you don't know their name)
    UI:SetSpeaker(STRINGS:Format("\\uE040"), true, sp.CurrentForm.Species, sp.CurrentForm.Form, sp.CurrentForm.Skin, sp.CurrentForm.Gender)
  elseif state == 2 then --Speaker is thinking to themselves. (Parenthesis are NOT included here.)
    UI:SetSpeaker("", true, sp.CurrentForm.Species, sp.CurrentForm.Form, sp.CurrentForm.Skin, sp.CurrentForm.Gender)
  else --Speaker speaks regularly
    UI:SetSpeaker(sp)
  end
  UI:SetSpeakerEmotion(emote)
  UI:WaitShowDialogue(txt)


end

function DirToNum(dir)
  --up is 0, upright is 1, ... up left is 7
  local num = -1
  if dir == Direction.Up then
    num = 0
  elseif dir == Direction.UpRight then
    num = 1
  elseif dir == Direction.Right then
    num = 2
  elseif dir == Direction.DownRight then
    num = 3
  elseif dir == Direction.Down then
    num = 4
  elseif dir == Direction.DownLeft then
    num = 5
  elseif dir == Direction.Left then
    num = 6
  elseif dir == Direction.UpLeft then
    num = 7
  end
  
  return num
  
end
--converts a number to a direction
function NumToDir(num)
  local dir = Direction.None
  if num % 8 == 0 then 
    dir = Direction.Up
  elseif num % 8 == 1 then
    dir = Direction.UpRight
  elseif num % 8 == 2 then
    dir = Direction.Right
  elseif num % 8 == 3 then
    dir = Direction.DownRight
  elseif num % 8 == 4 then
    dir = Direction.Down
  elseif num % 8 == 5 then
    dir = Direction.DownLeft
  elseif num % 8 == 6 then
    dir = Direction.Left
  elseif num % 8 == 7 then
    dir = Direction.UpLeft
  end

  return dir
end 
function Hop(chara, anim, height, duration, pause, sound)
  anim = anim or 'None'
  height = height or 10
  duration = duration or 10
  if pause == nil then pause = true end
  if sound == nil then sound = false end

  local animId = RogueEssence.Content.GraphicsManager.GetAnimIndex(anim)
  GROUND:CharSetAction(chara, RogueEssence.Ground.HopGroundAction(chara.Position, chara.Direction, animId, height, duration))
  
  if sound then
      SOUND:PlayBattleSE("EVT_Emote_Startled")
  end
  
  if pause then 
      GAME:WaitFrames(duration)
  end

end
-------------------------------
-- Entities Callbacks
-------------------------------
function room_player_and_partner.exit_Touch(obj, activator)
  local player = activator
  local partner = CH('Teammate1')
  if not SV.meeting_done then
    GAME:FadeOut(false, 20)
    SV.partner.entrance = 2
    GAME:EnterZone('thieves_hideout', -1, 6, 3)


  else
    SV.partner.entrance = 5
    GAME:FadeOut(false, 20)
    GAME:EnterZone('thieves_hideout', -1, 11, 10)


  end





end
function firstCutscene()
  local partner = CH('Teammate1')
  local player = CH('PLAYER')
  GAME:CutsceneMode(true)
  GAME:FadeIn(20)

  GAME:WaitFrames(60)
  Dialogue(partner, 3, "Worried", "I'm sorry I couldn't get you anything better,[pause=40] but this is all I could do in such a short time.")
  GAME:WaitFrames(60)
  Dialogue(player, 3, "Happy", "It's not that bad.[br]Thanks!")
  GAME:WaitFrames(60)
  Dialogue(partner, 3, "Worried", "So this is it, huh?[br]I finally get to have a partner and become a real team?")
  GAME:WaitFrames(80)
 
  GROUND:CharSetDrawEffect(partner, DrawEffect.Trembling)
  Dialogue(partner, 3, "Teary-Eyed", "I really thought this day would never come...")
  GAME:WaitFrames(40)
  Dialogue(player, 3, "Stunned", "Woah,[pause=30] are you okay?")
  GAME:WaitFrames(60)
  Dialogue(partner, 3, "Teary-Eyed", "Yeah, just...")
  GROUND:CharEndDrawEffect(partner, DrawEffect.Trembling)
  GAME:WaitFrames(60)
  Dialogue(partner, 3, "Happy", 'I never had someone I could call "partner" before.')
  Dialogue(partner, 3, "Happy", "You don't even know how much you being here means to me.")
  Dialogue(partner, 3, "Normal", "I know we didn't start in the best of terms,[pause=40] but I'm happy things turned out the way they did.")
  Dialogue(partner, 3, "Normal", "I've been dreaming of having a partner ever since I joined.")
  Dialogue(partner, 3, "Pain", "I was so envious of the rest of the teams and how they had someone they could always rely on while I didn't.")
  Dialogue(partner, 3, "Normal", "At least until now.")
 
  GAME:WaitFrames(60) 
  Dialogue(partner, 3, "Sad", 'I know that we are just "partners" and nowhere close to "friends" but...')
  Dialogue(partner, 3, "Happy", "Thank you, ".. player:GetDisplayName()..".[pause=50] Thank you so much.")
  GAME:WaitFrames(120)
  Dialogue(partner, 3, "Worried", "Sorry for ranting this much...")
  GAME:WaitFrames(40)
  Dialogue(player, 3, "Worried", "...")
  Dialogue(player, 3, "Normal", "Don't worry, ".. partner:GetDisplayName()..".[br]I don't mind.")

  GAME:WaitFrames(70)
  GROUND:CharAnimateTurn(partner, Direction.Right, 4, true)
  Dialogue(partner, 3, "Worried", partner:GetDisplayName().."...")
  GAME:WaitFrames(70)
  GROUND:CharAnimateTurn(partner, Direction.Left, 4, false)
  Dialogue(partner, 3, "Normal", "Hey, "..player:GetDisplayName().."...")
  Dialogue(player, 3, "Normal", "Yeah?")
  GAME:WaitFrames(50)
  Dialogue(partner, 3, "Worried", "This may be too much to ask, but...")
  GAME:WaitFrames(70)
  Dialogue(partner, 3, "Worried", "Would you mind...[pause=50] helping me out with picking a nickname?")
  
  Dialogue(player, 3, "Surprised", "Me?")
  GAME:WaitFrames(70)
  Dialogue(player, 3, "Worried", "Are you sure you shouldn't be the one to pick how you want to be called?")
  GAME:WaitFrames(50)
  Dialogue(partner, 3, "Worried", "That's what I thought at first.[br]But I've been like this for such a long time that I don't care anymore.")
  Dialogue(partner, 3, "Happy", "And now that I can,[pause=30] I want my partner to help me with it!")
  GAME:WaitFrames(50)
  Dialogue(partner, 3, "Worried", "If...[pause=40] that's alright with you, of course.")
  GAME:WaitFrames(70)
  Dialogue(player, 3, "Worried", "Well, I'm not very good at putting names on things, but...")
  Dialogue(player, 3, "Happy", "I can try!")
  GAME:WaitFrames(50)

  Dialogue(partner, 3, "Inspired", "You will?")
  Dialogue(player, 3, "Happy", "Sure!")
  Dialogue(player, 3, "Worried", "Now, let's see...")

  local loop = false 
	while not loop do
		UI:NameMenu("What could a good name for you be?", "", 60)
		UI:WaitForChoice()
		name = UI:ChoiceResult()
    if name == "" then 
      name = _DATA:GetMonster(GAME:GetPlayerPartyMember(1).CurrentForm.Species).Name:ToLocal() 
    end
  
      
		UI:ChoiceMenuYesNo("(Is [color=#fff30a]" .. name .. "[color] a good name for her?)")
		UI:WaitForChoice()
		loop = UI:ChoiceResult()
	end
  local partnerName = GAME:GetPlayerPartyMember(1)

  GAME:SetCharacterNickname(partnerName, name)
  GAME:WaitFrames(70)
  Dialogue(player, 3, "Normal", "How about ".. partner:GetDisplayName() .."?")
  Dialogue(player, 3, "Happy", "I think it suits you!")
  GAME:WaitFrames(50)
  Dialogue(partner, 3, "Worried", partner:GetDisplayName().."?")
  GAME:WaitFrames(80)
  Dialogue(player, 3, "Stunned", "I'm sorry.[br]I told you I wasn't too good at this...")
  Dialogue(partner, 3, "Surprised", "Not too good?!")
  Dialogue(partner, 3, "Inspired", "I love it![br]It's...[pause=60] perfect!")
  GAME:WaitFrames(70)
  Dialogue(player, 3, "Stunned", "You really think so?")
  Dialogue(partner, 3, "Inspired", "Of course I do![br]It's the best name ever!")
  --GAME:WaitFrames(20)
  Hop(partner, "None", 10, 10, true, false)
  Hop(partner, "None", 10, 10, false, false)
  Dialogue(partner, 3, "Inspired", "Thank you, thank you, thank you!")
  GAME:WaitFrames(70)
  Dialogue(player, 2, "Stunned", "(She looks so happy just by having a name...)")
  Dialogue(player, 2, "Happy", "(It's almost making me happy too!)")
  GAME:WaitFrames(70)
  Dialogue(partner, 3, "Happy", "Really, "..player:GetDisplayName().. ",[pause=40] you don't know how happy I am right now.")
  Dialogue(partner, 3, "Happy", "I'm so happy I found you in that clearing.")
  GAME:WaitFrames(90)
  GROUND:CharAnimateTurn(partner, Direction.Down, 6, true)
  GROUND:CharWaitAnim(partner, "DeepBreath")
  GAME:WaitFrames(20)
  GROUND:CharTurnToCharAnimated(partner, player, 4)
  Dialogue(partner, 3, "Normal", "It's getting pretty late.[br]We should go to sleep now if we don't want to walk around like zombies tomorrow.")
  GAME:WaitFrames(50)
  GROUND:CharSetAnim(partner, "Laying", true)
  GAME:WaitFrames(60)
  GROUND:CharSetAnim(player, "Laying", true)
  GAME:WaitFrames(80)
  Dialogue(partner, 3, "Normal", "Goodnight, " .. player:GetDisplayName() .. ".[br]See you tomorrow.")
  Dialogue(player, 3, "Normal", "Goodnight, " .. partner:GetDisplayName() .. ".")
  
  GAME:WaitFrames(90)
  UI:ResetSpeaker()
  UI:WaitShowDialogue("And thank you again, ".. player:GetDisplayName().. ".[br]Thank you for being my partner.")
  GAME:WaitFrames(60)

  GROUND:CharSetAnim(partner, "EventSleep", true)
  GAME:WaitFrames(120)
  
  Dialogue(player, 2, "Worried", "(So that's it, huh?)")
  Dialogue(player, 2, "Worried", "(This is official now.)[br](A thief in a guild of thieves...)")
  Dialogue(player, 2, "Worried", "(I never would have thought something like this could be happening to me...)")
  GAME:WaitFrames(60)
  Dialogue(player, 2, "Pain", "(And that's without counting the fact I'm a Pokémon now...)")
  GAME:WaitFrames(60)
  Dialogue(player, 2, "Worried", "(But why?)[br](Is there a reason why I got turned?)[br](Was it a coincidence it was ".. partner:GetDisplayName() .. " who found me and not any other Pokémon?)")
  GAME:WaitFrames(60)
  Dialogue(player, 2, "Pain", "(So many questions and so little answers...)")
  GAME:WaitFrames(80)
  Dialogue(player, 2, "Worried", "(Maybe that's for the best...)")
  Dialogue(player, 2, "Pain", "(I already have enough with having to get used to the fact I'll have to become a thief to have to worry about all of that...)")
  GAME:WaitFrames(80)
  Dialogue(player, 2, "Worried", "(Though...)")
  Dialogue(player, 2, "Worried", "(It may be because of the adrenaline of today or " .. partner:GetDisplayName() .. "'s enthusiasm, but...)")
  Dialogue(player, 2, "Inspired", "(I'm kind of excited!)")
  GAME:WaitFrames(80)
  Dialogue(player, 2, "Worried", "(But why is she so happy to have a total stranger as a partner?)")
  Dialogue(player, 2, "Worried", "(It's not like she has no friends here...)")
  GAME:WaitFrames(60)
  Dialogue(player, 2, "Worried", '(When she said that...[pause=50] about us being just "partners"...)')
  GAME:WaitFrames(60)
  Dialogue(player, 2, "Worried", "(It almost sounded like she was begging...)")
  GAME:WaitFrames(90)
  Dialogue(player, 2, "Sad", "(But even if we are better now, I don't want to give " ..partner:GetDisplayName() .. " fake hopes...)")
  Dialogue(player, 2, "Normal", "(I'll have to wait until I can make sure I can trust her fully,[pause=40] just like with the rest.)")
  Dialogue(player, 2, "Worried", "(They sound nice, but I shouldn't let my guard down too much.[pause=0] At least for now.)")
  GAME:WaitFrames(70)
  Dialogue(player, 2, "Worried", "(But there has to be someone I can trust here...)")
  GAME:WaitFrames(90)
  Dialogue(player, 2, "Worried", "(Maybe...[pause=60] I should let go of my prejudices and try and fully place my trust in my partner.)")
  GAME:WaitFrames(70)
  Dialogue(player, 2, "Worried", "(But that would mean telling her about me being a human...)")
  GAME:WaitFrames(50)
  Dialogue(player, 2, "Worried", "(Do I want to?)")
  GAME:WaitFrames(70)
  Dialogue(player, 2, "Worried", "(If she wants to be my friend, but she doesn't want to take the first step,[pause=40] maybe I should...)")
  Dialogue(player, 2, "Worried", "(Although...)")
  GAME:WaitFrames(50)
  Dialogue(player, 3, "Normal", partner:GetDisplayName() .. "?")
  GAME:WaitFrames(50)
  UI:ResetSpeaker()
  UI:WaitShowDialogue("...")
  GAME:WaitFrames(120)
  
  Dialogue(player, 3, "Sigh", "Figures...[br]She's asleep.")
  GAME:WaitFrames(70)
  Dialogue(player, 2, "Worried", "(It'll have to wait for tomorrow then...)")
  Dialogue(player, 2, "Worried", "(It's best if I try to sleep now.)")
  GAME:WaitFrames(70)
  UI:ResetSpeaker()
  UI:WaitShowDialogue("(Sleep tight, " .. partner:GetDisplayName().."...)")
  GAME:WaitFrames(80)
  GROUND:CharSetAnim(player, "EventSleep", true)
  GAME:WaitFrames(280)
  SOUND:FadeOutBGM(120)
  GAME:FadeOut(false, 60)
  



  

  SV.guildmasters_office.officially_joined = true
  SV.meeting_done = false
  SV.sleeping = false
  GROUND:Hide('fire')

  GROUND:RemoveMapStatus("dark")
  GROUND:Unhide('Kit')
  GROUND:CharSetAnim(partner, "Laying", true)
  GROUND:CharSetAnim(player, "Laying", true)
  GAME:MoveCamera(70, 142, 1, false)

  GAME:WaitFrames(260)
  SV.progression.chapter = 2
  UI:WaitShowTitle("Chapter 2\n\nThe first day\n", 20)
  GAME:WaitFrames(180)
  UI:WaitHideTitle(20)
  GAME:WaitFrames(180)
  UI:ResetSpeaker()
  UI:WaitShowDialogue("Hey.")
  GAME:WaitFrames(80)
  UI:WaitShowDialogue("HEY!")
  GAME:WaitFrames(80)
  GAME:FadeIn(20)
  GAME:WaitFrames(60)
  local kit = CH('Kit')
  Dialogue(kit, 3, "Happy", "Wakey wakey, team ".. GAME:GetTeamName() .. "!")
  Dialogue(kit, 3, "Normal", "It's a bright new day, and " .. player:GetDisplayName() .. "'s first too,[pause=40] so let's go to the morning meeting!")

  GROUND:CharSetDrawEffect(partner, DrawEffect.Trembling)
  GAME:WaitFrames(10)
  GROUND:CharSetDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(10)
  GROUND:CharEndDrawEffect(partner, DrawEffect.Trembling)
  GAME:WaitFrames(10)
  GROUND:CharEndDrawEffect(player, DrawEffect.Trembling)
  GAME:WaitFrames(60)
  Dialogue(partner, 3, "Pain", "Ugh...")
  Dialogue(player, 3, "Dizzy", "Wh-[pause=40]What?")
  GAME:WaitFrames(60)
  GROUND:CharSetAnim(partner, "Wake", false)
  GROUND:CharWaitAnim(player, "Wake")
  GAME:WaitFrames(20)
  GROUND:EntTurn(player, Direction.Left)
  GAME:WaitFrames(60)
  Dialogue(player, 3, "Stunned", kit:GetDisplayName().."?[br]What are you doing here?")
  GAME:WaitFrames(50)
  Dialogue(kit, 3, "Normal", "Well,[pause=30] as one of the oldest members here, I have the very important task of waking the guild up so they can go to the morning meeting.") 
  Dialogue(kit, 3, "Happy", "So let's start with your first day as a team, shall we?")
  GROUND:CharTurnToCharAnimated(player, partner, 4)
  Hop(partner, "None", 10)
  Dialogue(partner, 3, "Inspired", "Yeah! Let's do this!")
  GAME:WaitFrames(50)
  GROUND:CharTurnToCharAnimated(player, kit, 4)
  Dialogue(kit, 3, "Happy", "Such a big enthusiasm!")
  GAME:WaitFrames(50)

  Dialogue(kit, 3, "Normal", "You two are the last ones, so don't take too long to prepare.")
  Dialogue(partner, 3, "Happy", "We won't!")
  Dialogue(kit, 3, "Normal", "See you soon.")
  GROUND:MoveInDirection(kit, Direction.Left, 120, false, 2)
  GROUND:Hide('Kit')
  GAME:WaitFrames(80)
  GROUND:CharTurnToCharAnimated(player, partner, 4)
  Dialogue(player, 3, "Worried", "I guess that means it's time to get this day started, doesn't it?")
  Dialogue(partner, 3, "Normal", "It's always hard to wake up in the mornings, I know.")
  Dialogue(partner, 3, "Happy", "But we have to give our all, even if it's hard!")
  Dialogue(partner, 3, "Happy", "Let's go after him!")
  SOUND:PlayBGM("Wigglytuff's Guild.ogg", true) 
  GAME:MoveCamera(0, 0, 20, true)
  AI:SetCharacterAI(partner, "ai.ground_partner", CH('PLAYER'), partner.Position)
	AI:EnableCharacterAI(partner)
  partner.CollisionDisabled = true


  SV.refreshed_shop_stock = false


  GAME:CutsceneMode(false)

end
function room_player_and_partner.Teammate1_Action(obj, activator)
	GAME:CutsceneMode(true)

	if not SV.first_meeting_done then
	
	  GROUND:CharTurnToCharAnimated(obj, activator, 5)
	  GROUND:CharTurnToCharAnimated(activator, obj, 5)
	  Dialogue(obj, "Happy", "Come on, ".. activator:GetDisplayName() .."!")
	  Dialogue(obj, "Happy", "Let's not make the rest of the members wait and let's get to the meeting!")
	 
	end

	GAME:CutsceneMode(false)

end
return room_player_and_partner