--[[
    init.lua
    Created: 05/03/2024 14:05:44
    Description: Autogenerated script file for the map room_kit_and_lilith.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local room_kit_and_lilith = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---room_kit_and_lilith.Init(map)
--Engine callback function
function room_kit_and_lilith.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies()
  local partner = CH('Teammate1')
  AI:SetCharacterAI(partner, "ai.ground_partner", CH('PLAYER'), partner.Position)
  AI:EnableCharacterAI(partner)
  partner.CollisionDisabled = true
  if SV.guildmasters_office.officially_joined then
    GROUND:Hide('Kit')
    GROUND:Hide('Lilith')



  end
end

---room_kit_and_lilith.Enter(map)
--Engine callback function
function room_kit_and_lilith.Enter(map)

  GAME:FadeIn(20)

end

---room_kit_and_lilith.Exit(map)
--Engine callback function
function room_kit_and_lilith.Exit(map)


end

---room_kit_and_lilith.Update(map)
--Engine callback function
function room_kit_and_lilith.Update(map)


end

---room_kit_and_lilith.GameSave(map)
--Engine callback function
function room_kit_and_lilith.GameSave(map)
  local partner = CH('Teammate1')
  SV.partner.positionX = partner.Position.X
  SV.partner.positionY = partner.Position.Y
  SV.partner.direction = DirToNum(partner.Direction)

end

---room_kit_and_lilith.GameLoad(map)
--Engine callback function
function room_kit_and_lilith.GameLoad(map)
  local partners = CH('Teammate1')
  GROUND:TeleportTo(partners, SV.partner.positionX, SV.partner.positionY, NumToDir(SV.partner.direction))

	AI:SetCharacterAI(partners, "ai.ground_partner", CH('PLAYER'), partners.Position)
  AI:EnableCharacterAI(partners)
  partners.CollisionDisabled = true
  
  GAME:FadeIn(20)

end
function Dialogue(sp, state, emote, txt)
  if state == 0 then --Speaker is unknown and invisible
    UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  elseif state == 1 then --Speaker is unknown, but visible (AKA, you don't know their name)
    UI:SetSpeaker(STRINGS:Format("\\uE040"), true, sp.CurrentForm.Species, sp.CurrentForm.Form, sp.CurrentForm.Skin, sp.CurrentForm.Gender)
  elseif state == 2 then --Speaker is thinking to themselves. (Parenthesis are NOT included here.)
    UI:SetSpeaker("", true, sp.CurrentForm.Species, sp.CurrentForm.Form, sp.CurrentForm.Skin, sp.CurrentForm.Gender)
  else --Speaker speaks regularly
    UI:SetSpeaker(sp)
  end
  UI:SetSpeakerEmotion(emote)
  UI:WaitShowDialogue(txt)


end

function DirToNum(dir)
  --up is 0, upright is 1, ... up left is 7
  local num = -1
  if dir == Direction.Up then
    num = 0
  elseif dir == Direction.UpRight then
    num = 1
  elseif dir == Direction.Right then
    num = 2
  elseif dir == Direction.DownRight then
    num = 3
  elseif dir == Direction.Down then
    num = 4
  elseif dir == Direction.DownLeft then
    num = 5
  elseif dir == Direction.Left then
    num = 6
  elseif dir == Direction.UpLeft then
    num = 7
  end
  
  return num
  
end
--converts a number to a direction
function NumToDir(num)
  local dir = Direction.None
  if num % 8 == 0 then 
    dir = Direction.Up
  elseif num % 8 == 1 then
    dir = Direction.UpRight
  elseif num % 8 == 2 then
    dir = Direction.Right
  elseif num % 8 == 3 then
    dir = Direction.DownRight
  elseif num % 8 == 4 then
    dir = Direction.Down
  elseif num % 8 == 5 then
    dir = Direction.DownLeft
  elseif num % 8 == 6 then
    dir = Direction.Left
  elseif num % 8 == 7 then
    dir = Direction.UpLeft
  end

  return dir
end 
-------------------------------
-- Entities Callbacks
-------------------------------
function room_kit_and_lilith.exit_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  SV.partner.entrance = 4
  GAME:EnterZone('thieves_hideout', -1, 11, 7)
end
function room_kit_and_lilith.Kit_Action(obj, activator)

  local player = activator
  local partner = CH('Teammate1')
  local kit = obj
  local lilith = CH('Lilith')
  if not SV.guild.presented_to_illusion then

    GAME:CutsceneMode(true)

    GAME:FadeOut(false, 20)
    GROUND:CharTurnToChar(partner, kit)

    AI:DisableCharacterAI(partner)
    local marker = MRKR('me')
    GROUND:TeleportTo(player, marker.Position.X, marker.Position.Y, marker.Direction)
    local marker2 = MRKR('part')
    GROUND:TeleportTo(partner, marker2.Position.X, marker2.Position.Y, marker2.Direction)
    GAME:WaitFrames(60)
    GAME:FadeIn(20)
    GAME:WaitFrames(60)
    Dialogue(kit, 3, "Worried", "What are you even looking for?")
    Dialogue(kit, 3, "Worried", "You've been at it ever since we took those two to the entrance of the dungeon!")
    GAME:WaitFrames(30)
    GROUND:CharTurnToCharAnimated(lilith, kit, 4)
  
    Dialogue(lilith, 1, "Determined", "How many times do I have to tell you I'm not looking for anything!")
    Dialogue(lilith, 1, "Normal", "I'm taking care of the flowers!")

    SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
    GROUND:CharSetEmote(kit, "sweatdrop", 1)
    GAME:WaitFrames(90)
    Dialogue(kit, 3, "Stunned", "...[pause=50]And you're taking this long?")
    Dialogue(lilith, 1, "Happy", "Well, it takes time to make a garden flourish!")
    GAME:WaitFrames(60)
    Dialogue(kit, 3, "Stunned", "You have six flower pots and one of them is empty...")
    Dialogue(lilith, 1, "Determined", "Hey![pause=40] Don't question me about MY garden!")
    GAME:WaitFrames(60)

    Dialogue(kit, 3, "Worried", "Speaking of those two...[pause=40] How do you think they're doing?")
    Dialogue(kit, 3, "Worried", "You think ".. player:GetDisplayName() .. "'s gonna pass the test?")
    GAME:WaitFrames(60)
    GROUND:CharTurnToCharAnimated(lilith, player, 4)
    GAME:WaitFrames(60)
    GROUND:CharTurnToCharAnimated(lilith, kit, 4)
    GAME:WaitFrames(30)
    Dialogue(lilith, 1, "Sigh", "How about you turn around?")

    GROUND:CharSetEmote(kit, "question", 1)
    SOUND:PlaySE('Battle/EVT_Emote_Confused_2')
    GAME:WaitFrames(70)
    Dialogue(kit, 3, "Worried", "Why?")
    GAME:WaitFrames(60)
    Dialogue(partner, 3, "Worried", "Umm...[pause=40] Hi, " .. kit:GetDisplayName().."...")

		SOUND:PlaySE('Battle/EVT_Emote_Exclaim_2')
		GROUND:CharSetEmote(kit, "exclaim", 1)
    GROUND:CharTurnToCharAnimated(kit, partner, 3)
    GAME:WaitFrames(40)
    GROUND:CharTurnToCharAnimated(kit, player, 3)
    GAME:WaitFrames(60)
    Dialogue(kit, 3, "Surprised", "Woah![pause=40] Where did you two come from?!")
    SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
    GROUND:CharSetEmote(lilith, "sweatdrop", 1)
    GROUND:CharSetEmote(player, "sweatdrop", 1)
    GROUND:CharSetEmote(partner, "sweatdrop", 1)
    GAME:WaitFrames(80)
    Dialogue(lilith, 1, "Sigh", "Oh my god...")
    Dialogue(player, 3, "Surprised", "Wait, [pause=40]aren't you the [color=#00ff00]Zoroark[color] that-")
    Dialogue(kit, 3, "Normal", "Yup.")
    Dialogue(kit, 3, "Happy", "Glad to meet you in more regular circumstances!")
		GAME:WaitFrames(50)

    Dialogue(player, 3, "Stunned", "Like-[pause=50]Likewise...")
    GAME:WaitFrames(80)
    Dialogue(kit, 3, "Happy", "Oh come on![br]I was just acting as a bad guy![pause=0] Everyone knows that I wouldn't hurt a [color=#00ff00]Cutiefly[color]!")
    Dialogue(kit, 3, "Happy", "I only had to rip the guts out of someone once, so don't worry about it!")
    GAME:WaitFrames(120)
    SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
    GROUND:CharSetEmote(kit, "sweatdrop", 1)
    GAME:WaitFrames(80)
		Dialogue(kit, 3, "Normal", "Come on, don't look at me like that.")
		Dialogue(kit, 3, "Happy", "I was just joking!")
    GAME:WaitFrames(20)

		GROUND:CharSetEmote(player, "sweatdrop", 1)
		GROUND:CharSetEmote(partner, "sweatdrop", 1)
		SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
    GAME:WaitFrames(130)
		--If you have talked with Lupin before this, special dialogue is shown.
		if SV.guild.presented_to_lupin then
			Dialogue(player, 3, "Worried", "You won't happen to be friends with [color=#00ffff]Lupin[color], will you?")
			Dialogue(kit, 3, "Happy", "How did you know?")
      GAME:WaitFrames(50)
      Dialogue(lilith, 1, "Sigh", "Probably because you two share the same humor to an extent that someone that has known you for a few minutes can tell...")
			GAME:WaitFrames(50)

		end
    Dialogue(lilith, 1, "Normal", "Anyway.")
    Dialogue(lilith, 1, "Normal", player:GetDisplayName() .. ",[pause=10] remember how there was another voice when you were getting interrogated?")

		GAME:WaitFrames(50)
    
    Dialogue(player, 3, "Worried", "Was it you?")
    Dialogue(lilith, 1, "Joyous", "Yup, that was me!")
    Dialogue(lilith, 1, "Happy", "I'm "..lilith:GetDisplayName()..". "..kit:GetDisplayName().."'s partner and leader of team [color=#FFA5FF]Illusion[color].")
    GROUND:CharTurnToCharAnimated(kit, lilith, 4)
    Dialogue(kit, 3, "Determined", "Hey![br]I thought I was the leader of the team![br]That's what's officially written...!")
    GAME:WaitFrames(50)

    Dialogue(kit, 3, "Worried", "...right?")

    Dialogue(lilith, 3, "Normal", "No.")
    Dialogue(lilith, 3, "Normal", 'You were too distracted with fantasizing with being a "bad guy" while I did the paperwork.')
    Dialogue(lilith, 3, "Joyous", "And since I was the more mature one of the two, I took the liberty of becoming the leader.")
    GROUND:CharSetEmote(kit, "shock", 1)
    SOUND:PlaySE('Battle/EVT_Emote_Shock')
    Dialogue(kit, 3, "Surprised", "WHAT?!")
    Dialogue(kit, 3, "Teary-Eyed", "How could you...[br]I thought we were friends!")

    Dialogue(lilith, 3, "Happy", "Come on.[pause=0] You didn't even know you weren't the leader.[br]It doesn't really matter as long as we are together!")
    Dialogue(kit, 3, "Teary-Eyed", "...")
		GAME:WaitFrames(60)

    GROUND:CharSetEmote(kit, "happy", 0)
    Dialogue(kit, 3, "Joyous", "You're so corny sometimes![br]It's almost as if you like me or something!")

    GROUND:CharSetEmote(kit, "happy", 1)
    
    GROUND:CharSetEmote(lilith, "shock", 1)
    SOUND:PlaySE('Battle/EVT_Emote_Shock')
    GAME:WaitFrames(100)
    Dialogue(lilith, 3, "Stunned", "Yeah...[pause=50] haha...[br]You know how I am...")
    GAME:WaitFrames(80)
    Dialogue(kit, 3, "Normal", "Anyway.")
    GROUND:CharTurnToCharAnimated(kit, partner, 4)
    GROUND:CharTurnToCharAnimated(lilith, player, 4)
    GAME:WaitFrames(80)

    Dialogue(kit, 3, "Worried", "What are you two doing here?")
    Dialogue(partner, 3, "Normal", "I'm showing ".. player:GetDisplayName() .. " around and introducing him to everyone.")
   
    Dialogue(kit, 3, "Joyous", "Aha, so you're one of us now, huh?")
    Dialogue(kit, 3, "Joyous", "I knew the boss did good by giving you a chance!")
    Dialogue(lilith, 3, "Worried", "Who's your partner, "..player:GetDisplayName().."?")
    GAME:WaitFrames(60)
    Dialogue(partner, 3, "Worried", "It's me.")

    SOUND:PlaySE('Battle/EVT_Emote_Exclaim')
    GROUND:CharSetEmote(kit, "shock", 1)
    SOUND:PlaySE('Battle/EVT_Emote_Shock')
		GROUND:CharSetEmote(lilith, "notice", 1)

    GROUND:CharTurnToCharAnimated(lilith, partner, 3)
    GROUND:CharTurnToCharAnimated(kit, partner, 3)
    GAME:WaitFrames(90)
    Dialogue(kit, 3, "Surprised", "You?![br]I thought " .. player:GetDisplayName() .. " hated your guts!")
    Dialogue(player, 3, "Normal", "We made amends.")
    Dialogue(partner, 3, "Normal", "Yup.[pause=0] We talked about it just before the test.")

    Dialogue(lilith, 3, "Happy", "That's great![br]You finally have someone to accompany you on your missions!")
    Dialogue(kit, 3, "Sad", "Yeah,[pause=20] and now I owe her 20"..STRINGS:Format("\\uE024")..".")
    GAME:WaitFrames(60)
    Dialogue(player, 3, "Special3", "Did you two bet on this?")

    GROUND:CharTurnToCharAnimated(kit, player, 3)
    GROUND:CharTurnToCharAnimated(lilith, player, 3)
    GAME:WaitFrames(60)

    Dialogue(lilith, 3, "Normal", kit:GetDisplayName().." bet that you two would end up fighting each other before getting to the final part of the test.")
    Dialogue(lilith, 3, "Joyous", "So now he owes me twenty bucks!")
    GROUND:CharTurnToCharAnimated(kit, lilith, 4)

    Dialogue(kit, 3, "Normal", "I'm gonna take the money from the funds of our team anyway...")

    GROUND:CharTurnToCharAnimated(lilith, kit, 4)
    GAME:WaitFrames(50)

    Dialogue(lilith, 3, "Happy", "You aren't touching our money unless you want a Shadow Claw used on you while you sleep,[pause=40] got it?")
    
    SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
		GROUND:CharSetEmote(kit, "sweatdrop", 1)
    GAME:WaitFrames(90)
    Dialogue(kit, 3, "Stunned", "Okay...[br]Sorry.")
    GAME:WaitFrames(100)
    GROUND:CharSetEmote(player, "happy", 0)
    GROUND:CharSetEmote(partner, "happy", 0)
    GROUND:CharTurnToCharAnimated(kit, player, 4)
    GROUND:CharTurnToCharAnimated(lilith, partner, 4)
    Dialogue(player, 3, "Joyous", "You guys are just like a couple!")
    Dialogue(partner, 3, "Joyous", "You'll never change!")
    SOUND:PlaySE("Battle/EVT_Emote_Sweatdrop")
		GROUND:CharSetEmote(kit, "sweatdrop", 1)
		GROUND:CharSetEmote(lilith, "sweatdrop", 1)
    GAME:WaitFrames(90)
    Dialogue(lilith, 3, "Stunned", "Why does this always end up happening?")
    Dialogue(kit, 3, "Sigh", "I've given up on trying to find an answer to that...")
    GROUND:CharSetEmote(player, "happy", 1)
    GROUND:CharSetEmote(partner, "happy", 1)
    GAME:WaitFrames(70)
    Dialogue(partner, 3, "Normal", "That aside...[br]Were you guys doing something before we arrived?")
    GAME:WaitFrames(50)

    Dialogue(lilith, 3, "Worried", "Well, we were readying ourselves to go to bed already...")
    GROUND:CharTurnToCharAnimated(kit, lilith, 4)
    Dialogue(kit, 3, "Normal", "No,[pause=40] I was the one trying to get stuff set, but you were too busy checking if your flowers were alive.")
    GROUND:CharTurnToCharAnimated(kit, player, 4)
    Dialogue(kit, 3, "Normal", "Spoiler alert:[pause=40] they were.")
    GAME:WaitFrames(80)
    GROUND:CharTurnToCharAnimated(lilith, kit, 4)

    Dialogue(lilith, 3, "Normal", "I'm gonna start criticizing you every time you go and get drunk with [color=#00ffff]Lupin[color] every time you say something about my garden.")
    
    GROUND:CharTurnToCharAnimated(kit, lilith, 4)
    Hop(kit, "None", 10, 10, true, "Battle/EVT_Emote_Complain_2")
    Hop(kit, "None", 10, 10, true, "Battle/EVT_Emote_Complain_2")
    Dialogue(kit, 3, "Determined", "It was ONE time!")
    Dialogue(lilith, 3, "Joyous", "Yeah, and you two went in and quite literally kissed [color=#00ffff]Ma'am[color] so much that she almost fired you!")
    Dialogue(lilith, 3, "Joyous", "You're lucky she was half-drunk too or you'd be out of here!")
    GAME:WaitFrames(60)
   
    Dialogue(kit, 3, "Stunned", "We did what?")
    GAME:WaitFrames(60)

    Dialogue(lilith, 3, "Stunned", "You didn't know?")
    GAME:WaitFrames(60)

    Dialogue(kit, 3, "Worried", "Was that the reason why everyone laughed when they saw us?")
    Dialogue(lilith, 3, "Joyous", "Yeah, we promised to keep the secret as long as we could,[pause=40] so don't tell [color=#00ffff]Lupin[color]!")
    GROUND:CharTurnToCharAnimated(kit, partner, 4)
   
    Dialogue(kit, 3, "Stunned", partner:GetDisplayName()..", did you know about this?")
    GROUND:CharTurnToCharAnimated(player, partner, 4)
    GROUND:CharTurnToCharAnimated(lilith, partner, 4)
    GAME:WaitFrames(60)
    Dialogue(partner, 3, "Happy", "Yeah!")
    Dialogue(partner, 3, "Joyous", "It was very funny!")
    GAME:WaitFrames(60)
    Dialogue(kit, 3, "Stunned", "...")
    GROUND:CharTurnToCharAnimated(kit, player, 4)

    Dialogue(kit, 3, "Stunned", "Now you're gonna tell me " .. player:GetDisplayName() .. " knew about it too!")
    GAME:WaitFrames(60)

    Dialogue(player, 3, "Stunned", "No-[pause=40] No I didn't...")
    GAME:WaitFrames(70)
    GROUND:CharTurnToCharAnimated(lilith, kit, 4)
    GROUND:CharAnimateTurn(kit, Direction.UpRight, 4, true) -- char, dir, frames in each dir, ccws
    
    GAME:WaitFrames(20)
    GROUND:CharSetEmote(kit, "sweating", 1)
    SOUND:PlaySE('Battle/EVT_Emote_Sweating')
    GAME:WaitFrames(120)
    Dialogue(kit, 2, "Pain", "(Please, tell me they're lying...)")
    GAME:WaitFrames(70)

    GROUND:CharTurnToCharAnimated(lilith, player, 4)
    Dialogue(lilith, 3, "Normal", "Well, it was nice meeting you and all, but we should probably start preparing ourselves for bed.")
    Dialogue(lilith, 3, "Happy", "I better see you both tomorrow in the briefing!")
    Dialogue(partner, 3, "Happy", "You will,[pause=30] don't worry!")
    GROUND:CharTurnToCharAnimated(kit, player, 4)
    Dialogue(kit, 3, "Pain", "See you...")

    GAME:FadeOut(false, 20)
    GROUND:CharTurnToChar(kit, lilith)
    GROUND:EntTurn(lilith, Direction.UpLeft)


    GAME:CutsceneMode(false)
    AI:SetCharacterAI(partner, "ai.ground_partner", CH('PLAYER'), partner.Position)
    AI:EnableCharacterAI(partner)
    partner.CollisionDisabled = true
    SV.guild.presented_to_illusion = true
    GAME:FadeIn(20)

  else
    GROUND:CharTurnToChar(kit, player)
    Dialogue(kit, 3, "Normal", "It was nice chatting with you both.")
    Dialogue(kit, 3, "Normal", "I'm excited to see what you can do, "..player:GetDisplayName() .. ".")
    Dialogue(kit, 3, "Worried", "And sorry if we hurt you when we were in that room...")
    Dialogue(kit, 3, "Normal", "But you gotta understand it had to be like that.")
    Dialogue(kit, 3, "Happy", "Hopefully you won't hold any resentment towards us.")
    GROUND:CharTurnToChar(kit, lilith)


  end



end

function Hop(chara, anim, height, duration, pause, sound)
  anim = anim or 'None'
  height = height or 10
  duration = duration or 10
  if pause == nil then pause = true end
  if sound == nil then sound = false end

  local animId = RogueEssence.Content.GraphicsManager.GetAnimIndex(anim)
  GROUND:CharSetAction(chara, RogueEssence.Ground.HopGroundAction(chara.Position, chara.Direction, animId, height, duration))
  
  if sound then
      SOUND:PlayBattleSE("EVT_Emote_Startled")
  end
  
  if pause then 
      GAME:WaitFrames(duration)
  end

end



return room_kit_and_lilith

